<script lang="ts" setup>
import { IconUniJumpPage } from '@tg/icons'

</script>

<template>
  <div>
    <div class="text-tg-text-white text-[20px] font-semibold leading-[1.32] @md:text-[28px]">
      Random Number Generation
    </div>
    <div class="text-tg-secondary-light mt-[16px] text-[16px] leading-[1.5] @md:text-[18px]">
      For each verifiable bet, a client seed, a server seed, a nonce and a cursor are used as the input parameters for the <a class="text-tg-text-white text-[14px]" href="https://en.wikipedia.org/wiki/Random_number_generation" target="_blank">random number generation <IconUniJumpPage class="text-[12px]" /></a> function. This function utilises the cryptographic hash function <a class="text-tg-text-white text-[14px]" href="https://en.wikipedia.org/wiki/HMAC" target="_blank">HMAC_SHA256 <IconUniJumpPage class="text-[12px]" /></a> to generate bytes which are then used as the foundation for how we generate provably fair random outcomes on our platform.
    </div>
    <div class="text-tg-text-white scroll-x bg-tg-secondary-grey mt-[16px] rounded-[4px] p-[16px] text-[16px] leading-[1.5] @md:text-[18px]">
      <pre><code style="font-family: monospace,monospace;font-size: 1em;">// Random number generation based on following inputs: serverSeed, clientSeed, nonce and cursor
function byteGenerator({ serverSeed, clientSeed, nonce, cursor }) {
  // Setup curser variables
  let currentRound = Math.floor(cursor / 32);
  let currentRoundCursor = cursor;
  currentRoundCursor -= currentRound * 32;

  // Generate outputs until cursor requirement fullfilled
  while (true) {
    // HMAC function used to output provided inputs into bytes
    const hmac = createHmac('sha256', serverSeed);
    hmac.update(`${clientSeed}:${nonce}:${currentRound}`);
    const buffer = hmac.digest();

    // Update curser for next iteration of loop
    while (currentRoundCursor &lt; 32) {
      yield Number(buffer[currentRoundCursor]);
      currentRoundCursor += 1;
    }
    currentRoundCursor = 0;
    currentRound += 1;
  }
}</code></pre>
    </div>
    <div class="text-tg-text-white mt-[16px] text-[20px] font-semibold leading-[1.32] @md:text-[28px]">
      Server Seed
    </div>
    <div class="text-tg-secondary-light mt-[16px] text-[16px] leading-[1.5] @md:text-[18px]">
      The server seed is generated by our system as a random 64-character hex string. You are then provided with an encrypted hash of that generated server seed before you place any bets. The reason we provide you with the encrypted form of the server seed is to ensure that the un-hashed server seed cannot be changed by the casino operator, and that the player cannot calculate the results beforehand.
    </div>
    <div class="text-tg-secondary-light mt-[16px] text-[16px] leading-[1.5] @md:text-[18px]">
      To reveal the server seed from its hashed version, the seed must be rotated by the player, which triggers the replacement with a newly generated one.
    </div>
    <div class="text-tg-secondary-light mt-[16px] text-[16px] leading-[1.5] @md:text-[18px]">
      From this point you are able to verify that the hashed server seed matches that of the un-hashed server seed. This process can be verified via our un-hashed server seed function found in the menu above.
    </div>
    <div class="text-tg-text-white mt-[16px] text-[20px] font-semibold leading-[1.32] @md:text-[28px]">
      Client Seed
    </div>
    <div class="text-tg-secondary-light mt-[16px] text-[16px] leading-[1.5] @md:text-[18px]">
      The client seed belongs to the player and is used to ensure they have influence on the randomness of the outcomes generated. Without this component of the algorithm, the server seed alone would have complete leverage over the outcome of each bet.
    </div>
    <div class="text-tg-secondary-light mt-[16px] text-[16px] leading-[1.5] @md:text-[18px]">
      All players are free to edit and change their client seed regularly to create a new chain of random upcoming outcomes. This ensures the player has absolute control over the generation of the result, similar to cutting the deck at a brick and mortar casino.
    </div>
    <div class="text-tg-secondary-light mt-[16px] text-[16px] leading-[1.5] @md:text-[18px]">
      During registration, a client seed is created for you by your browser, to ensure your initial experience with the site goes uninterrupted. Whilst this randomly generated client seed is considered suitable, we highly recommend that you choose your own, so that your influence is included in the randomness.
    </div>
    <div class="text-tg-secondary-light mt-[16px] text-[16px] leading-[1.5] @md:text-[18px]">
      You can do this via the fairness modal.
    </div>
    <div class="text-tg-text-white mt-[16px] text-[20px] font-semibold leading-[1.32] @md:text-[28px]">
      Nonce
    </div>
    <div class="text-tg-secondary-light mt-[16px] text-[16px] leading-[1.5] @md:text-[18px]">
      The nonce is simply a number that increments as every new bet is made. Due to the nature of the SHA256 cryptographic function, this creates a completely new result each time, without having to generate a new client seed and server seed.
    </div>
    <div class="text-tg-secondary-light mt-[16px] text-[16px] leading-[1.5] @md:text-[18px]">
      The implementation of nonce, ensures we remain committed to your client seed and server seed pair, whilst generating new results for each bet placed.
    </div>
    <div class="text-tg-text-white mt-[16px] text-[20px] font-semibold leading-[1.32] @md:text-[28px]">
      Cursor (Incremental Number)
    </div>
    <div class="text-tg-secondary-light mt-[16px] text-[16px] leading-[1.5] @md:text-[18px]">
      We use 4 bytes of data to generate a single game result, and because SHA256 is limited to 32 bytes, we utilise this implementation of a cursor to give us the ability to create more game events without having to modify our provable fair algorithm.
    </div>
    <div class="text-tg-secondary-light mt-[16px] text-[16px] leading-[1.5] @md:text-[18px]">
      The cursor is only iterated over when the game being played requires the generation of more than 8 (32 bytes / 4 bytes) possible outcomes. For example: when we need to use more than 8 cards in a game of blackjack.
    </div>
    <div class="text-tg-secondary-light mt-[16px] text-[16px] leading-[1.5] @md:text-[18px]">
      The cursor starts as 0 and gets increased by 1 every time the 32 bytes are returned by the HMAC_SHA256 function. If we don’t require more than 8 random numbers to be generated for the game events, then the curser does not increment as there is no need to generate any additional possible game outcomes.
    </div>
    <div class="text-tg-text-white mt-[16px] text-[18px] font-semibold leading-[1.32]">
      Games with More Than 1 Incremental Number:
    </div>
    <ul class="ml-[32px] mt-[16px] list-disc text-[16px] leading-[1.32] @md:text-[18px]">
      <!-- <li class="mb-[8px]">
        Hilo (Unlimited to cover required amount of cards)
      </li>
      <li class="mb-[8px]">
        Keno (2 increments for every game due to 10 possible outcomes)
      </li>
      <li class="mb-[8px]">
        Mines (3 increments per game for 24 possible bomb locations)
      </li> -->
      <li class="mb-[8px]">
        Plinko (2 increments per game to cover possible 16 decisions)
      </li>
      <!-- <li class="mb-[8px]">
        Video Poker (7 increments to generate 52 possible cards in a full deck)
      </li>
      <li class="mb-[8px]">
        Diamond Poker (2 increments to cover 10 diamonds: 5 per player/dealer)
      </li>
      <li class="mb-[8px]">
        Slots (The incremental number is only utilised for bonus rounds)
      </li> -->
    </ul>
    <div class="text-tg-text-white mt-[16px] text-[18px] font-semibold leading-[1.32]">
      Games with More Than 1 Incremental Number (Represented as Default Value 0):
    </div>
    <ul class="ml-[32px] mt-[16px] list-disc text-[16px] @md:text-[18px]">
      <li class="mb-[8px] leading-[1.32]">
        Dice
      </li>
      <li class="mb-[8px] leading-[1.32]">
        Limbo
      </li>
    </ul>
  </div>
</template>

<style lang="scss" scoped></style>
