import { getEnv } from './main'

const { VITE_OFFICIAL_NAME } = getEnv()

export const antiMoneyLaundering = {
  'en-US': {
    title: 'Anti-Money Laundering & Counter-Terrorism Financing Statement',
    sections: [
      {
        heading: '1. Business Model',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} was established in 2017 and currently supports users in over 169 countries worldwide.`,
          `As part of its global operations, ${VITE_OFFICIAL_NAME} has implemented compliance measures aligned with its services and products, designed to reasonably prevent and detect illegal activities on its platform.`,
          'These measures include customer onboarding and compliance screening, as well as transaction-based controls.',
        ],
      },
      {
        heading: '2. Company Policy Statement',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} is not a financial institution under Curaçao law and is therefore not directly subject to regulations applicable to certain financial institutions, remittance providers, or virtual asset service providers.`,
          `However, under the 2016 Anti-Money Laundering and Counter-Terrorism Financing ("AML / CFT") rules provided by the Curaçao Gaming Control Board for the Curaçao jurisdiction, ${VITE_OFFICIAL_NAME} strictly prohibits and refuses the use of its products for any illegal activity, including money laundering, terrorism financing, or violations of trade sanctions, in line with AML laws, regulations, and standards of various countries.`,
          `${VITE_OFFICIAL_NAME} continuously monitors the standards set by the Financial Action Task Force ("FATF"), relevant gaming industry bodies, and the Curaçao Gaming Control Board, and will take necessary actions in response to legal changes.`,
          `${VITE_OFFICIAL_NAME} aims to follow global best practices to prevent its products from being used to facilitate such activities. These best practices include:`,
          '• Implementing written policies, procedures, and controls reasonably designed to prevent money laundering, terrorism financing, and trade sanctions violations;',
          '• Appointing a Compliance Officer, where appropriate, to oversee the implementation of policies, procedures, and controls;',
          '• Providing relevant education and training to personnel; and',
          '• Conducting independent review, monitoring, and maintenance of policies, procedures, and controls.',
        ],
      },
      {
        heading: '3. Definitions',
        paragraphs: [
          'Money Laundering: The process of making illegally obtained funds appear legitimate, typically in three steps: placement, layering, and integration.',
          'Placement: Depositing illegally obtained funds into traditional financial institutions via deposits or other means.',
          'Layering: Separating criminal proceeds from their source through complex financial transactions, such as converting cash into traveler\'s checks, money orders, wire transfers, letters of credit, stocks, bonds, or purchasing assets.',
          'Integration: Using seemingly legitimate transactions to obscure illegally obtained funds, allowing laundered funds to be reintroduced into normal use by criminals.',
          'Suspicious Activity: Transactions by users or non-users that indicate the transaction may be conducted for fraudulent or illegal purposes.',
          'Sanctions: Measures imposed by the international community to prohibit or restrict sanctioned activities. For example, they may be used to:',
          '• Encourage a target country or regime to change behavior;',
          '• Apply pressure on a target country to comply with set objectives;',
          '• Serve as an enforcement tool when international peace and security are threatened and diplomatic efforts fail;',
          '• Prevent and suppress financing of terrorists or terrorist acts.',
        ],
      },
      {
        heading: '4. Governance & Oversight',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} has appointed a Chief Compliance Officer ("CCO") responsible for coordinating AML policies and program implementation.`,
          `The CCO’s duties include developing the AML program, updating AML policies with other ${VITE_OFFICIAL_NAME} stakeholders, evaluating new regulatory requirements, and investigating potentially suspicious or unusual activity.`,
          `${VITE_OFFICIAL_NAME} also provides regular AML training to all employees.`,
        ],
      },
      {
        heading: '5. Know Your Customer (KYC) & Transaction Monitoring',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} applies legally required user due diligence and ongoing monitoring measures. ${VITE_OFFICIAL_NAME} strives to prevent users from engaging in illegal or unauthorized activities.`,
          `Compliance is enforced through a combination of ${VITE_OFFICIAL_NAME}’s software features and service agreements to ensure adherence to applicable laws.`,
        ],
      },
      {
        heading: '5.A Customer Due Diligence (CDD)',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} uses a risk-based CDD approach to understand the nature and purpose of the relationship between users and the ${VITE_OFFICIAL_NAME} platform, creating a risk profile for each customer.`,
          `During account registration, ${VITE_OFFICIAL_NAME} collects certain written and non-written information relevant to the account type and services provided. Different CDD measures are maintained for different accounts and services.`,
          `Example CDD procedures require users to complete ${VITE_OFFICIAL_NAME}’s Customer Identification Program (CIP), which includes:`,
          `• Collecting baseline information (e.g., wallet address, email) via ${VITE_OFFICIAL_NAME}’s onboarding portal at account creation;`,
          '• Monitoring risk profiles associated with the cryptocurrency wallets funding user accounts;',
          '• Recording information used to identify the user; and',
          '• Checking whether the user appears on known or suspected terrorist lists provided by financial institutions.',
          'These steps are implemented through:',
          '• Identity & Age Verification: Third-party providers help verify the validity of identity information and other KYC materials, confirm the user is legally allowed, and ensure the user is not located in fully sanctioned or prohibited jurisdictions. Global sanctions lists are checked using onboarding information such as wallet addresses.',
          `• Customer Information: ${VITE_OFFICIAL_NAME} collects detailed information to form a reasonable belief about the user’s identity, aligned with the user’s risk profile. This may include wallet address, name, address, country, date of birth, or postal code (collectively "KYC Information"). ${VITE_OFFICIAL_NAME} collects this information before issuing funding addresses (e.g., QR codes). Currently, non-natural person users are not allowed. ${VITE_OFFICIAL_NAME} may rely on another entity to perform some or all elements of CIP.`,
          '• Geoblocking for Prohibited Jurisdictions: Contracted users must confirm they are not in countries where services are prohibited, verified through IP-based geoblocking. Users must not be subject to U.S., EU, or other global sanctions or watchlists, including individuals or entities in fully sanctioned U.S. jurisdictions (Iran, Cuba, North Korea, Syria, and Crimea). Risk-based measures, including KYC and IP geoblocking, are used to verify these statements.',
          `Contracts prohibit onboarding users from restricted jurisdictions. Users are informed that ${VITE_OFFICIAL_NAME} does not provide services in restricted jurisdictions. These policies stem from ${VITE_OFFICIAL_NAME}’s risk, fraud prevention, and AML standards, as well as assessments of service permissibility in specific jurisdictions.`,
        ],
      },
      {
        heading: '5.B Enhanced Due Diligence (EDD) & Ongoing Monitoring',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} continuously monitors users to detect behavior or indicators potentially linked to money laundering or terrorism financing. A set of red-flag indicators helps identify such behavior and triggers further action during customer assessments.`,
          'If a red flag is triggered, the user account may be suspended and subject to enhanced due diligence (EDD).',
          'EDD may include, but is not limited to, collecting and verifying: full name; nationality; permanent address; identification numbers (tax ID, passport, foreigner ID, or other government-issued ID); identity documents; source of funds and wealth.',
          `${VITE_OFFICIAL_NAME} may use third-party service providers to verify any of the above information to establish a reasonable basis for understanding the true identity of the user if required by their activities.`,
        ],
      },
      {
        heading: '5.C Acceptance Policy',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} will not accept and will block users who:`,
          '• Fail to provide requested identity information;',
          '• Submit false identity documents;',
          '• Attempt to misrepresent their location;',
          '• Are from restricted or prohibited jurisdictions;',
          '• Are subject to U.S., EU, or other global sanctions or watchlists;',
          '• Have long-term gambling addiction or mental health issues;',
          '• Conduct transactions from restricted jurisdictions or with prohibited funding sources.',
          `${VITE_OFFICIAL_NAME} reserves the right to block or suspend players for any other reason.`,
        ],
      },
      {
        heading: '5.D Transaction Monitoring',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} strictly complies with economic and trade sanctions applicable in its operating jurisdictions.`,
          `To enforce this, ${VITE_OFFICIAL_NAME} has established a transaction monitoring program using a combination of internally developed rule-based systems and third-party systems to identify and detect anomalies in real-time and through ongoing monitoring.`,
          `This program outlines how ${VITE_OFFICIAL_NAME} identifies unusual activity through employee and customer identity verification, law enforcement queries, other referrals, transaction and monitoring system reports, and focuses on investigating, assessing, and recording alerts for identified or potentially suspicious activities.`,
          `${VITE_OFFICIAL_NAME} follows these processes to achieve these goals:`,
          `• Sanctions & Restricted Jurisdiction Monitoring: ${VITE_OFFICIAL_NAME} monitors transactions from sanctioned or prohibited jurisdictions. Additional due diligence may be applied when users withdraw balances. A mix of manual and automated monitoring identifies red-flag behavior. Suspicious withdrawals may be rejected or additional information may be requested. Users attempting to fund accounts from prohibited jurisdictions (disclosed in the ${VITE_OFFICIAL_NAME} UI and updated internally) may be restricted. For example, funding from wallets associated with U.S. exchanges may be blocked.`,
          `• Sanctions Screening: Before issuing ${VITE_OFFICIAL_NAME} funding addresses, wallet addresses are screened against applicable sanctions databases using third-party blockchain forensics providers, such as Chainalysis. Wallets are regularly re-screened.`,
          '• Suspicious Activity Detection: Account activity is monitored for unusual transaction size, frequency, patterns, or types, considering risk factors and red flags. Reports of unusual, high-risk, or suspicious activity are generated regularly.',
          '• Anti-Mixing Measures: Software is used to detect suspicious deposit or withdrawal patterns. Cases are reviewed individually based on risk, and users may be asked to explain their platform usage.',
          '• Chainalysis Review: All crypto deposits and withdrawals, direct or indirect, are reviewed for signs of fraud or suspicious activity. Accounts flagged for potential illegal activity are suspended and reviewed. High-risk accounts may be required to provide proof of funds. Withdrawals to high-risk addresses, as determined by Chainalysis risk scores, may be denied.',
          '• Withdrawal Threshold KYC: Any account reaching a withdrawal threshold based on its risk profile will be suspended until sufficient KYC due diligence is completed.',
        ],
      },
      {
        heading: 'Additional Ongoing Monitoring Controls',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} has implemented the following procedures to complement its KYC and ongoing monitoring programs:`,
          `• Multiple Account Detection: Third-party software detects users operating multiple accounts by linking accounts accessed from the same device. Cases are reviewed individually based on risk, and users may be asked to explain their platform usage. ${VITE_OFFICIAL_NAME} accounts are funded via local (non-custodial) or custodial wallets. Beyond Chainalysis screening, user activity on the ${VITE_OFFICIAL_NAME} platform is monitored, and all withdrawals must comply with ${VITE_OFFICIAL_NAME} and third-party verification processes. Peer-to-peer account transfers within the ${VITE_OFFICIAL_NAME} platform are prohibited. Attempts to bypass these restrictions are treated as red flags.`,
          '• Timezone Monitoring: Device timezone information is monitored and cross-checked with restricted jurisdictions to detect attempts to hide connection sources using geolocation tools.',
          `• Product & Service Review: Additional procedures are in place to prevent users from abusing the platform. Users must comply with ${VITE_OFFICIAL_NAME}’s robust user terms. Safeguards mitigate abuse risks, including policies restricting which assets may be uploaded to the platform. ${VITE_OFFICIAL_NAME} maintains a list of allowable assets and prohibits anonymity-enhanced technologies (mixers, tumblers, certain coins/tokens). Any detected use of these technologies is banned.`,
          `• Vendor Management: ${VITE_OFFICIAL_NAME} partners with reputable third-party service providers as part of its compliance infrastructure. Key vendors are regularly evaluated to ensure services meet contractual obligations, and corrective measures are taken if needed. Vendors may be required to provide information as part of the vendor review process.`,
          '• Compliance Innovation: Emerging compliance solutions are monitored to assess applicability. Pilot programs may be conducted to evaluate effectiveness. Blockchain-native tools include anti-fraud services, on-chain KYC providers, and other tools reflecting technical characteristics of blockchain platforms.',
          `• Education & Training: Under legal counsel and CCO oversight, ${VITE_OFFICIAL_NAME} provides regular AML, CFT, and sanctions compliance training to employees as needed.`,
          `• Reporting: ${VITE_OFFICIAL_NAME} is required by law to report any unusual or suspicious transactions. Customers confirmed on sanctions lists or involved in money laundering, terrorism financing, or other criminal activities are reported to regulatory authorities as suspicious activity.`,
        ],
      },
    ],
  },
  'tl-PH': {
    title: 'Anti-Money Laundering & Counter-Terrorism Financing Statement',
    sections: [
      {
        heading: '1. Business Model',
        paragraphs: [
          `Itinatag ang ${VITE_OFFICIAL_NAME} noong 2017 at kasalukuyang sumusuporta sa mga gumagamit sa higit sa 169 na bansa sa buong mundo.`,
          `Bilang bahagi ng pandaigdigang operasyon nito, ipinatupad ng ${VITE_OFFICIAL_NAME} ang mga hakbang sa pagsunod na naaayon sa mga serbisyo at produkto nito, na idinisenyo upang makatwiran na maiwasan at matukoy ang mga ilegal na aktibidad sa platform nito. Kasama sa mga hakbang na ito ang onboarding ng customer at compliance screening, pati na rin ang mga kontrol batay sa transaksyon.`,
        ],
      },
      {
        heading: '2. Company Policy Statement',
        paragraphs: [
          `Ang ${VITE_OFFICIAL_NAME} ay hindi isang institusyong pinansyal sa ilalim ng batas ng Curaçao at samakatuwid ay hindi direktang saklaw ng mga regulasyon na naaangkop sa ilang institusyong pinansyal, tagapagbigay ng remittance, o tagapagbigay ng serbisyo ng virtual asset.`,
          `Gayunpaman, sa ilalim ng 2016 Anti-Money Laundering at Counter-Terrorism Financing ("AML / CFT") rules na ibinigay ng Curaçao Gaming Control Board para sa hurisdiksyon ng Curaçao, mahigpit na ipinagbabawal ng ${VITE_OFFICIAL_NAME} at tinatanggihan ang paggamit ng mga produkto nito para sa anumang ilegal na aktibidad, kabilang ang money laundering, financing ng terorismo, o paglabag sa mga trade sanctions, alinsunod sa mga batas, regulasyon, at pamantayan ng AML ng iba't ibang bansa.`,
          `Patuloy na minomonitor ng ${VITE_OFFICIAL_NAME} ang mga pamantayan na itinakda ng Financial Action Task Force ("FATF"), mga kaugnay na katawan ng industriya ng gaming, at ng Curaçao Gaming Control Board, at gagawa ng kinakailangang aksyon bilang tugon sa mga pagbabago sa batas.`,
          `Layunin ng ${VITE_OFFICIAL_NAME} na sundin ang pinakamahuhusay na global practices upang maiwasan ang paggamit ng mga produkto nito sa ganitong mga aktibidad. Kasama sa mga best practices na ito ang:`,
          '• Pagpapatupad ng nakasulat na mga polisiya, pamamaraan, at kontrol na makatwirang idinisenyo upang maiwasan ang money laundering, financing ng terorismo, at paglabag sa trade sanctions;',
          '• Pagtatalaga ng Compliance Officer, kung naaangkop, upang pangasiwaan ang pagpapatupad ng mga polisiya, pamamaraan, at kontrol;',
          '• Pagbibigay ng kaukulang edukasyon at pagsasanay sa mga tauhan; at',
          '• Pagsasagawa ng independiyenteng pagsusuri, pagmamanman, at pagpapanatili ng mga polisiya, pamamaraan, at kontrol.',
        ],
      },
      {
        heading: '3. Definitions',
        paragraphs: [
          'Money Laundering: Proseso ng pagpapakita na lehitimo ang ilegal na nakuhang pondo, karaniwang sa tatlong hakbang: placement, layering, at integration.',
          'Placement: Pagdedeposito ng ilegal na nakuhang pondo sa mga tradisyonal na institusyong pinansyal sa pamamagitan ng deposito o iba pang paraan.',
          'Layering: Paghiwalay ng mga kriminal na kita mula sa pinagmulan nito sa pamamagitan ng kumplikadong transaksyong pinansyal, tulad ng pagpapalit ng cash sa traveler\'s checks, money orders, wire transfers, letters of credit, stocks, bonds, o pagbili ng mga asset.',
          'Integration: Paggamit ng tila lehitimong transaksyon upang itago ang ilegal na nakuhang pondo, na nagpapahintulot sa mga nalinis na pondo na maibalik sa normal na paggamit ng mga kriminal.',
          'Suspicious Activity: Mga transaksyon ng mga gumagamit o hindi gumagamit na nagpapahiwatig na maaaring isagawa ang transaksyon para sa mapanlinlang o ilegal na layunin.',
          'Sanctions: Mga hakbang na ipinataw ng internasyonal na komunidad upang ipagbawal o limitahan ang mga sanctioned na aktibidad. Halimbawa, maaaring gamitin ito upang:',
          '• Hikayatin ang target na bansa o rehimen na baguhin ang kanilang asal;',
          '• Magpatupad ng presyon sa target na bansa upang sumunod sa itinakdang layunin;',
          '• Maging kasangkapan sa pagpapatupad kapag ang pandaigdigang kapayapaan at seguridad ay nanganganib at nabigo ang diplomatikong pagsisikap;',
          '• Pigilan at sugpuin ang financing ng mga terorista o gawaing terorista.',
        ],
      },
      {
        heading: '4. Governance & Oversight',
        paragraphs: [
          `Itinalaga ng ${VITE_OFFICIAL_NAME} ang isang Chief Compliance Officer ("CCO") na responsable sa pag-coordinate ng AML policies at pagpapatupad ng programa.`,
          `Kabilang sa mga tungkulin ng CCO ang pagbuo ng AML program, pag-update ng AML policies kasama ang iba pang stakeholder ng ${VITE_OFFICIAL_NAME}, pagsusuri ng mga bagong regulasyon, at pagsisiyasat sa mga potensyal na kahina-hinala o kakaibang aktibidad.`,
          `Nagbibigay din ang ${VITE_OFFICIAL_NAME} ng regular na AML training sa lahat ng empleyado.`,
        ],
      },
      {
        heading: '5. Know Your Customer (KYC) & Transaction Monitoring',
        paragraphs: [
          `Ipinapatupad ng ${VITE_OFFICIAL_NAME} ang legally required na user due diligence at patuloy na monitoring measures.`,
          `Nagsusumikap ang ${VITE_OFFICIAL_NAME} na pigilan ang mga gumagamit mula sa paglahok sa ilegal o hindi awtorisadong mga aktibidad.`,
          `Ang pagsunod ay ipinapatupad sa pamamagitan ng kombinasyon ng mga software feature ng ${VITE_OFFICIAL_NAME} at mga service agreement upang matiyak ang pagsunod sa naaangkop na batas.`,
        ],
      },
      {
        heading: '5.A Customer Due Diligence (CDD)',
        paragraphs: [
          `Gumagamit ang ${VITE_OFFICIAL_NAME} ng risk-based na CDD approach upang maunawaan ang kalikasan at layunin ng relasyon sa pagitan ng mga gumagamit at ng ${VITE_OFFICIAL_NAME} platform, at lumikha ng risk profile para sa bawat customer.`,
          `Sa pagrehistro ng account, kinokolekta ng ${VITE_OFFICIAL_NAME} ang ilang nakasulat at hindi nakasulat na impormasyon na may kaugnayan sa uri ng account at mga serbisyong ibinibigay. Iba’t ibang CDD measures ang pinananatili para sa iba’t ibang account at serbisyo.`,
          `Halimbawa ng CDD procedures ay nangangailangan sa mga gumagamit na kumpletuhin ang ${VITE_OFFICIAL_NAME} Customer Identification Program (CIP), na kinabibilangan ng:`,
          `• Pagkolekta ng baseline information (hal. wallet address, email) sa pamamagitan ng ${VITE_OFFICIAL_NAME} onboarding portal sa paglikha ng account;`,
          '• Pagmo-monitor ng risk profiles na kaugnay sa cryptocurrency wallets na nagpopondo sa mga user account;',
          '• Pagrerekord ng impormasyon na ginagamit upang tukuyin ang gumagamit; at',
          '• Pagsusuri kung ang gumagamit ay nasa kilala o pinaghihinalaang terrorist lists na ibinigay ng mga institusyong pinansyal.',
          'Ang mga hakbang na ito ay ipinatutupad sa pamamagitan ng:',
          '• Identity & Age Verification: Tinutulungan ng third-party providers na beripikahin ang bisa ng identity information at iba pang KYC materials, tiyakin na legal na pinapayagan ang gumagamit, at siguraduhing hindi sila nasa fully sanctioned o prohibited jurisdictions. Sinusuri ang global sanctions lists gamit ang onboarding information tulad ng wallet addresses.',
          `• Customer Information: Kinokolekta ng ${VITE_OFFICIAL_NAME} ang detalyadong impormasyon upang makabuo ng makatwirang paniniwala tungkol sa pagkakakilanlan ng gumagamit, alinsunod sa risk profile nito. Maaaring kabilang dito ang wallet address, pangalan, address, bansa, petsa ng kapanganakan, o postal code (sama-samang tinatawag na "KYC Information"). Kinokolekta ng ${VITE_OFFICIAL_NAME} ang impormasyong ito bago magbigay ng funding addresses (hal. QR codes). Sa kasalukuyan, hindi pinapayagan ang non-natural person users. Maaaring umasa ang ${VITE_OFFICIAL_NAME} sa ibang entidad upang isagawa ang ilan o lahat ng bahagi ng CIP.`,
          '• Geoblocking for Prohibited Jurisdictions: Kinakailangang kumpirmahin ng mga kontraktadong user na hindi sila nasa mga bansang ipinagbabawal ang serbisyo, na tinitiyak sa pamamagitan ng IP-based geoblocking. Hindi dapat saklaw ng U.S., EU, o iba pang global sanctions o watchlists ang mga gumagamit, kabilang ang mga indibidwal o entidad sa fully sanctioned U.S. jurisdictions (Iran, Cuba, North Korea, Syria, at Crimea). Ginagamit ang risk-based measures, kabilang ang KYC at IP geoblocking, upang beripikahin ang mga pahayag na ito.',
          `Pinagbabawal ng mga kontrata ang onboarding ng mga gumagamit mula sa restricted jurisdictions. Ipinapaalam sa mga user na hindi nagbibigay ang ${VITE_OFFICIAL_NAME} ng serbisyo sa mga restricted jurisdictions. Ang mga patakarang ito ay nagmula sa risk, fraud prevention, at AML standards ng ${VITE_OFFICIAL_NAME}, pati na rin sa pagsusuri ng permissibility ng serbisyo sa mga partikular na hurisdiksyon.`,
        ],
      },
      {
        heading: '5.B Enhanced Due Diligence (EDD) & Ongoing Monitoring',
        paragraphs: [
          `Patuloy na minomonitor ng ${VITE_OFFICIAL_NAME} ang mga gumagamit upang matukoy ang mga kilos o indikasyon na maaaring kaugnay ng money laundering o financing ng terorismo. May set ng red-flag indicators na tumutulong upang matukoy ang ganitong kilos at nagti-trigger ng karagdagang aksyon sa customer assessments.`,
          'Kung may ma-trigger na red flag, maaaring suspendihin ang user account at sumailalim sa enhanced due diligence (EDD).',
          'Maaaring kabilang sa EDD, ngunit hindi limitado sa, ang pagkolekta at pag-verify ng: pangalan; nasyonalidad; permanenteng address; identification numbers (tax ID, passport number at issuing country, foreigner ID, o ibang government-issued ID); identity documents; at source ng pondo at kayamanan.',
          `Maaaring gumamit ang ${VITE_OFFICIAL_NAME} ng third-party service providers upang beripikahin ang alinman sa mga impormasyon sa itaas upang magkaroon ng makatwirang batayan sa pag-unawa sa totoong pagkakakilanlan ng gumagamit kung kinakailangan ng kanilang aktibidad.`,
        ],
      },
      {
        heading: '5.C Acceptance Policy',
        paragraphs: [
          `Hindi tatanggapin at ibablock ng ${VITE_OFFICIAL_NAME} ang mga gumagamit na:`,
          '• Hindi magbigay ng hinihinging identity information;',
          '• Mag-submit ng pekeng identity documents;',
          '• Magpanggap tungkol sa kanilang lokasyon;',
          '• Mula sa restricted o prohibited jurisdictions;',
          '• Saklaw ng U.S., EU, o iba pang global sanctions o watchlists;',
          '• May long-term gambling addiction o mental health issues;',
          '• Magsagawa ng transaksyon mula sa restricted jurisdictions o may prohibited funding sources.',
          `Nirereseva ng ${VITE_OFFICIAL_NAME} ang karapatan na i-block o i-suspend ang mga player para sa anumang iba pang dahilan.`,
        ],
      },
      {
        heading: '5.D Transaction Monitoring',
        paragraphs: [
          `Mahigpit na sumusunod ang ${VITE_OFFICIAL_NAME} sa economic at trade sanctions na naaangkop sa mga hurisdiksyon ng operasyon nito.`,
          `Upang ipatupad ito, nagtatag ang ${VITE_OFFICIAL_NAME} ng transaction monitoring program gamit ang kombinasyon ng internally developed rule-based systems at third-party systems upang tukuyin at matukoy ang anomalies sa real-time at patuloy na monitoring.`,
          `Itinutukoy ng programang ito kung paano natutukoy ng ${VITE_OFFICIAL_NAME} ang hindi pangkaraniwang aktibidad sa pamamagitan ng employee at customer identity verification, law enforcement queries, iba pang referrals, transaction at monitoring system reports, at nakatuon sa pagsisiyasat, pagtatasa, at pagrerekord ng alerts para sa tinukoy o potensyal na suspicious activities.`,
          `Sinusunod ng ${VITE_OFFICIAL_NAME} ang mga prosesong ito upang maabot ang mga layuning ito:`,
          `• Sanctions & Restricted Jurisdiction Monitoring: Minomonitor ng ${VITE_OFFICIAL_NAME} ang mga transaksyon mula sa sanctioned o prohibited jurisdictions. Maaaring magpatupad ng karagdagang due diligence kapag nagwi-withdraw ng balances ang user. Isang kombinasyon ng manual at automated monitoring ang tumutukoy sa “red-flag” behavior. Maaaring tanggihan ang suspicious withdrawals o humingi ng karagdagang impormasyon mula sa mga recipients. Maaaring limitahan ang mga gumagamit na sumusubok magpondo ng account mula sa prohibited jurisdictions (ipinapakita sa ${VITE_OFFICIAL_NAME} UI at ina-update internally). Halimbawa, maaaring i-block ang funding mula sa wallets na kaugnay ng U.S. exchanges. Maaaring magbigay ng karagdagang impormasyon ang mga user upang pabulaanan ang anumang suspension bilang bahagi ng ongoing monitoring at KYC standards.`,
          `• Sanctions Screening: Bago magbigay ng ${VITE_OFFICIAL_NAME} funding addresses, sinusuri ang wallet addresses laban sa naaangkop na sanctions databases gamit ang third-party blockchain forensics providers, tulad ng Chainalysis. Regular na nire-re-screen ang wallets.`,
          '• Suspicious Activity Detection: Minomonitor ang account activity para sa hindi pangkaraniwang laki, dalas, pattern, o uri ng transaksyon, isinasaalang-alang ang risk factors at red flags. Regular na nire-report ang unusual, high-risk, o suspicious activity.',
          '• Anti-Mixing Measures: Ginagamit ang software upang tukuyin ang suspicious deposit o withdrawal patterns. Ibinabagal ang kaso batay sa risk, at maaaring hingin sa mga user na ipaliwanag ang paggamit ng platform.',
          '• Chainalysis Review: Lahat ng crypto deposits at withdrawals, direkta o hindi direkta, ay nire-review para sa senyales ng fraud o suspicious activity. Ang mga accounts na na-flag para sa potensyal na ilegal na aktibidad ay sinususpinde at nire-review. Maaaring hingin sa high-risk accounts na magbigay ng proof of funds. Maaaring tanggihan ang withdrawals sa “high-risk” addresses ayon sa Chainalysis risk scores.',
          '• Withdrawal Threshold KYC: Anumang account na umabot sa withdrawal threshold batay sa risk profile nito ay sinususpinde hanggang sa makumpleto ang sapat na KYC due diligence.',
        ],
      },
      {
        heading: 'Karagdagang Ongoing Monitoring Controls',
        paragraphs: [
          `Ipinatupad ng ${VITE_OFFICIAL_NAME} ang sumusunod na mga pamamaraan upang suportahan ang KYC at ongoing monitoring programs:`,
          `• Multiple Account Detection: Gumagamit ang ${VITE_OFFICIAL_NAME} ng third-party software upang tukuyin ang mga gumagamit na may maraming account. Ikinokonekta ng software ang mga account na na-access mula sa parehong device. Sinusuri ang mga kaso batay sa risk, at maaaring hingin sa mga user na ipaliwanag ang paggamit ng platform. Ang ${VITE_OFFICIAL_NAME} accounts ay pinopondo sa pamamagitan ng local (non-custodial) o custodial wallets. Bukod sa Chainalysis screening, minomonitor ang user activity sa ${VITE_OFFICIAL_NAME} platform, at lahat ng withdrawals ay dapat sumunod sa ${VITE_OFFICIAL_NAME} at third-party verification processes. Ipinagbabawal ang peer-to-peer account transfers sa loob ng ${VITE_OFFICIAL_NAME} platform. Ang mga pagtatangka na lampasan ang mga limitasyong ito ay itinuturing na red flags.`,
          `• Timezone Monitoring: Minomonitor ng ${VITE_OFFICIAL_NAME} ang device timezone information at kinukumpara sa restricted jurisdictions upang matukoy ang pagtatangka na itago ang pinagmulan ng koneksyon gamit ang geolocation tools.`,
          `• Product & Service Review: May karagdagang procedures upang maiwasan ang pang-aabuso ng mga user sa platform. Dapat sumunod ang mga user sa robust user terms ng ${VITE_OFFICIAL_NAME}. Ipinapatupad ng ${VITE_OFFICIAL_NAME} ang safeguards upang bawasan ang risk ng pang-aabuso, tulad ng mga patakaran na naglilimita kung aling assets ang maaaring i-upload sa platform. Pinapanatili ng ${VITE_OFFICIAL_NAME} ang listahan ng allowable assets at ipinagbabawal ang anonymous-enhanced technologies (mixers, tumblers, ilang coins/tokens). Ang anumang nakitang paggamit ng mga teknolohiyang ito ay ipinagbabawal.`,
          `• Vendor Management: Nakikipagtulungan ang ${VITE_OFFICIAL_NAME} sa mga kagalang-galang na third-party service providers bilang bahagi ng compliance infrastructure. Regular na sinusuri ang key vendors upang matiyak na natutugunan ang contractual obligations, at isinasagawa ang corrective measures kung kinakailangan. Maaaring hilingin sa vendors na magbigay ng impormasyon bilang bahagi ng vendor review process.`,
          `• Compliance Innovation: Bukod sa vendor management, minomonitor ng ${VITE_OFFICIAL_NAME} ang mga emerging compliance solutions upang suriin ang applicability nito. Maaaring isagawa ang pilot programs upang suriin ang bisa. Kasama sa blockchain-native tools ang anti-fraud services, on-chain KYC providers, at iba pang tools na nagpapakita ng teknikal na katangian ng blockchain platforms.`,
          `• Education & Training: Sa ilalim ng legal counsel at CCO oversight, nagbibigay ang ${VITE_OFFICIAL_NAME} ng regular AML, CFT, at sanctions compliance training sa mga empleyado ayon sa pangangailangan.`,
          `• Reporting: Kinakailangan ng batas na i-report ng ${VITE_OFFICIAL_NAME} ang anumang unusual o suspicious transactions. Ang mga customer na nakumpirmang nasa sanctions lists o sangkot sa money laundering, financing ng terorismo, o iba pang kriminal na aktibidad ay i-report sa regulatory authorities bilang suspicious activity.`,
        ],
      },
    ],
  },
  'pt-BR': {
    title: 'Declaração de Prevenção à Lavagem de Dinheiro e ao Financiamento do Terrorismo',
    sections: [
      {
        heading: '1. Modelo de Negócios',
        paragraphs: [
          `A ${VITE_OFFICIAL_NAME} foi fundada em 2017 e atualmente atende usuários em mais de 169 países em todo o mundo.`,
          `Como parte de suas operações globais, a ${VITE_OFFICIAL_NAME} implementou medidas de conformidade alinhadas aos seus serviços e produtos, projetadas para prevenir e detectar atividades ilegais em sua plataforma.`,
          'Essas medidas incluem o cadastro de clientes e a verificação de conformidade, bem como controles baseados em transações.',
        ],
      },
      {
        heading: '2. Política da Empresa',
        paragraphs: [
          `A ${VITE_OFFICIAL_NAME} não é uma instituição financeira sob a lei de Curaçao e, portanto, não está diretamente sujeita às regulamentações aplicáveis a determinadas instituições financeiras, provedores de remessas ou provedores de serviços de ativos virtuais.`,
          `No entanto, de acordo com as normas de 2016 de Combate à Lavagem de Dinheiro e ao Financiamento do Terrorismo ("AML / CFT") estabelecidas pelo Conselho de Controle de Jogos de Curaçao para a jurisdição de Curaçao, a ${VITE_OFFICIAL_NAME} proíbe e recusa estritamente o uso de seus produtos para qualquer atividade ilegal, incluindo lavagem de dinheiro, financiamento do terrorismo ou violações de sanções comerciais, em conformidade com as leis, regulamentos e padrões de AML de diversos países.`,
          `A ${VITE_OFFICIAL_NAME} monitora continuamente os padrões estabelecidos pelo Grupo de Ação Financeira Internacional ("GAFI"), órgãos relevantes do setor de jogos e o Conselho de Controle de Jogos de Curaçao, e tomará as medidas necessárias em resposta a mudanças na legislação.`,
          `A ${VITE_OFFICIAL_NAME} busca seguir as melhores práticas globais para evitar que seus produtos sejam usados para facilitar tais atividades. Essas melhores práticas incluem:`,
          '• Implementar políticas, procedimentos e controles por escrito, razoavelmente projetados para prevenir a lavagem de dinheiro, o financiamento do terrorismo e violações de sanções comerciais;',
          '• Nomear um Diretor de Conformidade, quando apropriado, para supervisionar a implementação de políticas, procedimentos e controles;',
          '• Fornecer educação e treinamento relevantes para o pessoal; e',
          '• Realizar revisão, monitoramento e manutenção independentes de políticas, procedimentos e controles.',
        ],
      },
      {
        heading: '3. Definições',
        paragraphs: [
          'Lavagem de dinheiro: O processo de fazer com que fundos obtidos ilegalmente pareçam legítimos, geralmente em três etapas: colocação, ocultação e integração.',
          'Colocação: Depositar fundos obtidos ilegalmente em instituições financeiras tradicionais por meio de depósitos ou outros meios.',
          'Ocultação: Separar os proventos criminosos de sua origem por meio de transações financeiras complexas, como a conversão de dinheiro em cheques de viagem, ordens de pagamento, transferências eletrônicas, cartas de crédito, ações, títulos ou a compra de ativos.',
          'Integração: Utilização de transações aparentemente legítimas para obter fundos ilegalmente de forma obscura, permitindo que fundos lavados sejam reintroduzidos em uso normal por criminosos.',
          'Atividade Suspeita: Transações realizadas por usuários ou não usuários que indicam que a transação pode ser conduzida para fins fraudulentos ou ilegais.',
          'Sanções: Medidas impostas pela comunidade internacional para proibir ou restringir atividades. Por exemplo, podem ser usadas para:',
          '• Incentivar um país ou regime alvo a mudar seu comportamento;',
          '• Pressionar um país alvo para que cumpra os objetivos estabelecidos;',
          '• Servir como instrumento de aplicação da lei quando a paz e a segurança internacionais estiverem ameaçadas e os esforços diplomáticos falharem;',
          '• Prevenir e reprimir o financiamento de terroristas ou atos terroristas.',
        ],
      },
      {
        heading: '4. Governança e Supervisão',
        paragraphs: [
          `A ${VITE_OFFICIAL_NAME} nomeou um Diretor de Conformidade ("CCO") responsável por coordenar as políticas de AML e a implementação do programa.`,
          `As atribuições do CCO incluem o desenvolvimento do programa de AML, a atualização das políticas de AML com outras partes interessadas da ${VITE_OFFICIAL_NAME}, a avaliação de novos requisitos regulatórios e a investigação de atividades potencialmente suspeitas ou incomuns.`,
          `A ${VITE_OFFICIAL_NAME} também oferece treinamento regular em AML para todos os funcionários.`,
        ],
      },
      {
        heading: '5. Conheça Seu Cliente (KYC) e Monitoramento de Transações',
        paragraphs: [
          `A ${VITE_OFFICIAL_NAME} aplica medidas de diligência prévia do usuário e monitoramento contínuo, conforme exigido por lei.`,
          `A ${VITE_OFFICIAL_NAME} se esforça para impedir que os usuários se envolvam em atividades ilegais ou não autorizadas.`,
          `A conformidade é garantida por meio de uma combinação de recursos de software e contratos de serviço da ${VITE_OFFICIAL_NAME}, assegurando a adesão às leis aplicáveis.`,
        ],
      },
      {
        heading: '5.A Diligência Prévia do Cliente (DPC)',
        paragraphs: [
          `A ${VITE_OFFICIAL_NAME} utiliza uma abordagem de DPC baseada em risco para compreender a natureza e a finalidade do relacionamento entre os usuários e a plataforma ${VITE_OFFICIAL_NAME}, criando um perfil de risco para cada cliente.`,
          `Durante o cadastro da conta, a ${VITE_OFFICIAL_NAME} coleta determinadas informações escritas e não escritas relevantes para o tipo de conta e os serviços prestados. Diferentes medidas de DPC são mantidas para diferentes contas e serviços.`,
          `O exemplo de DPC exige que os usuários concluam o Programa de Identificação do Cliente (CIP) da ${VITE_OFFICIAL_NAME}, que inclui:`,
          `• Coletar informações básicas (por exemplo, endereço da carteira, e-mail) por meio do portal de integração da ${VITE_OFFICIAL_NAME} no momento da criação da conta;`,
          '• Monitorar os perfis de risco associados às carteiras de criptomoedas que financiam as contas dos usuários;',
          '• Registrar as informações usadas para identificar o usuário; e',
          '• Verificar se o usuário consta em listas de terroristas conhecidos ou suspeitos fornecidas por instituições financeiras.',
          'Essas etapas são implementadas por meio de:',
          '• Verificação de Identidade e Idade: Fornecedores terceirizados ajudam a verificar a validade das informações de identidade e outros materiais KYC, confirmam se o usuário tem permissão legal e garantem que ele não esteja localizado em jurisdições totalmente sancionadas ou proibidas. Listas de sanções globais são verificadas usando informações de cadastro, como endereços de carteira.',
          `• Informações do Cliente: A ${VITE_OFFICIAL_NAME} coleta informações detalhadas para formar uma crença razoável sobre a identidade do usuário, alinhada ao seu perfil de risco. Isso pode incluir endereço de carteira, nome, endereço residencial, país, data de nascimento ou CEP (coletivamente, “Informações KYC”). A ${VITE_OFFICIAL_NAME} coleta essas informações antes de emitir endereços de financiamento (por exemplo, códigos QR). Atualmente, usuários que não sejam pessoas físicas não são permitidos. A ${VITE_OFFICIAL_NAME} pode contar com outra entidade para executar alguns ou todos os elementos do CIP.`,
          '• Bloqueio Geográfico para Jurisdições Proibidas: Os usuários contratados devem confirmar que não estão em países onde os serviços são proibidos, verificado por meio de bloqueio geográfico baseado em IP. Os usuários não devem estar sujeitos a sanções ou listas de vigilância dos EUA, da UE ou de outros países, incluindo indivíduos ou entidades em jurisdições totalmente sancionadas pelos EUA (Irã, Cuba, Coreia do Norte, Síria e Crimeia). Medidas baseadas em risco, incluindo KYC e bloqueio geográfico de IP, são usadas para verificar essas declarações.',
          `Os contratos proíbem a integração de usuários de jurisdições restritas. Os usuários são informados de que a ${VITE_OFFICIAL_NAME} não presta serviços em jurisdições restritas. Essas políticas decorrem dos padrões de risco, prevenção de fraudes e AML da ${VITE_OFFICIAL_NAME}, bem como das avaliações de permissibilidade do serviço em jurisdições específicas.`,
        ],
      },
      {
        heading: '5.B Due Diligence Aprimorada e Monitoramento Contínuo',
        paragraphs: [
          `A ${VITE_OFFICIAL_NAME} monitora continuamente os usuários para detectar comportamentos ou indicadores potencialmente ligados à lavagem de dinheiro ou ao financiamento do terrorismo. Um conjunto de indicadores de alerta ajuda a identificar esses comportamentos e aciona ações adicionais durante as avaliações dos clientes.`,
          'Se um alerta for acionado, a conta do usuário poderá ser suspensa e sujeita a uma diligência reforçada (EDD).',
          'A EDD pode incluir, entre outras coisas, a coleta e verificação de: nome completo; nacionalidade; endereço permanente; números de identificação (CPF, passaporte, documento de estrangeiro ou outro documento governamental com foto); documentos de identidade; e origem dos fundos e patrimônio.',
          `A ${VITE_OFFICIAL_NAME} poderá utilizar prestadores de serviços terceirizados para verificar qualquer uma das informações acima, a fim de estabelecer uma base razoável para compreender a verdadeira identidade do usuário, caso isso seja necessário para as suas atividades.`,
        ],
      },
      {
        heading: '5.C Política de Aceitação',
        paragraphs: [
          `A ${VITE_OFFICIAL_NAME} não aceitará e bloqueará usuários que:`,
          '• Não fornecer as informações de identidade solicitadas;',
          '• Apresentar documentos de identidade falsos;',
          '• Tentar deturpar sua localização;',
          '• Ser de jurisdições restritas ou proibidas;',
          '• Estar sujeito a sanções ou listas de vigilância dos EUA, da UE ou de outros países;',
          '• Ter vício em jogos de azar ou problemas de saúde mental de longa data;',
          '• Realizar transações a partir de jurisdições restritas ou com fontes de financiamento proibidas.',
          `A ${VITE_OFFICIAL_NAME} reserva-se o direito de bloquear ou suspender jogadores por qualquer outro motivo.`,
        ],
      },
      {
        heading: 'Monitoramento de Transações',
        paragraphs: [
          `A ${VITE_OFFICIAL_NAME} cumpre rigorosamente as sanções econômicas e comerciais aplicáveis nas jurisdições em que opera.`,
          `Para garantir isso, a ${VITE_OFFICIAL_NAME} estabeleceu um programa de monitoramento de transações que utiliza uma combinação de sistemas internos baseados em regras e sistemas de terceiros para identificar e detectar anomalias em tempo real e por meio de monitoramento contínuo.`,
          `Este programa descreve como a ${VITE_OFFICIAL_NAME} identifica atividades incomuns por meio da verificação de identidade de funcionários e clientes, consultas às autoridades policiais, outras referências, relatórios de transações e do sistema de monitoramento, e concentra-se na investigação, avaliação e registro de alertas para atividades identificadas ou potencialmente suspeitas.`,
          `A ${VITE_OFFICIAL_NAME} segue estes processos para atingir esses objetivos:`,
          `• Monitoramento de Sanções e Jurisdições Restritas: A ${VITE_OFFICIAL_NAME} monitora transações provenientes de jurisdições sancionadas ou proibidas. Uma análise mais rigorosa pode ser aplicada quando os usuários realizam saques. Uma combinação de monitoramento manual e automatizado identifica comportamentos suspeitos. Saques suspeitos podem ser rejeitados ou informações adicionais podem ser solicitadas aos destinatários. Usuários que tentarem depositar fundos a partir de jurisdições proibidas (divulgadas na interface da ${VITE_OFFICIAL_NAME} e atualizadas internamente) podem ter suas contas restringidas. Por exemplo, depósitos provenientes de carteiras associadas a corretoras dos EUA podem ser bloqueados. Os usuários podem fornecer informações adicionais para contestar qualquer suspensão, como parte do monitoramento contínuo e dos padrões KYC.`,
          `• Verificação de sanções: Antes de emitir endereços de financiamento ${VITE_OFFICIAL_NAME}, os endereços das carteiras são verificados em relação aos bancos de dados de sanções aplicáveis, utilizando provedores terceirizados de análise forense de blockchain, como a Chainalysis. As carteiras são verificadas novamente regularmente.`,
          '• Detecção de atividades suspeitas: A atividade da conta é monitorada em busca de transações incomuns em termos de tamanho, frequência, padrões ou tipos, considerando fatores de risco e sinais de alerta. Relatórios de atividades incomuns, de alto risco ou suspeitas são gerados regularmente.',
          '• Medidas Anti-Mistura: Utilizamos software para detectar padrões suspeitos de depósito ou saque. Os casos são analisados individualmente com base no risco, e os usuários podem ser solicitados a explicar o uso da plataforma.',
          '• Análise da Chainalysis: Todos os depósitos e saques em criptomoedas, diretos ou indiretos, são analisados em busca de indícios de fraude ou atividade suspeita. Contas sinalizadas por potencial atividade ilegal são suspensas e revisadas. Contas de alto risco podem ser obrigadas a comprovar a origem dos fundos. Saques para endereços considerados de "alto risco", conforme determinado pela pontuação de risco da Chainalysis, podem ser negados.',
          '• Limite de Saque KYC: Independentemente da localização ou afiliação, qualquer conta que atingir um limite de saque com base em seu perfil de risco será suspensa até que a devida diligência KYC seja concluída.',
        ],
      },
      {
        heading: 'Controles adicionais de monitoramento contínuo',
        paragraphs: [
          `A ${VITE_OFFICIAL_NAME} implementou os seguintes procedimentos para complementar seus programas de KYC e monitoramento contínuo:`,
          `• Detecção de Contas Múltiplas: A ${VITE_OFFICIAL_NAME} utiliza software de terceiros para detectar usuários que operam múltiplas contas. O software vincula contas acessadas a partir do mesmo dispositivo. Os casos são analisados individualmente com base no risco, e os usuários podem ser solicitados a explicar o uso da plataforma. As contas ${VITE_OFFICIAL_NAME} são financiadas por meio de carteiras locais (não custodiadas) ou custodiadas. Além da verificação da Chainalysis, a atividade do usuário na plataforma ${VITE_OFFICIAL_NAME} é monitorada, e todos os saques devem estar em conformidade com os processos de verificação da ${VITE_OFFICIAL_NAME} e de terceiros. Transferências ponto a ponto dentro da plataforma ${VITE_OFFICIAL_NAME} são proibidas. Tentativas de burlar essas restrições são consideradas suspeitas.`,
          `• Monitoramento de fuso horário: O ${VITE_OFFICIAL_NAME} monitora as informações de fuso horário do dispositivo e realiza verificações cruzadas com jurisdições restritas para detectar tentativas de ocultar as fontes de conexão usando ferramentas de geolocalização.`,
          `• Análise de Produto e Serviço: Procedimentos adicionais estão em vigor para evitar que os usuários abusem da plataforma. Os usuários devem cumprir os termos de uso rigorosos da ${VITE_OFFICIAL_NAME}. A ${VITE_OFFICIAL_NAME} implementa medidas de segurança para mitigar os riscos de abuso, como políticas que restringem quais ativos podem ser carregados na plataforma. A ${VITE_OFFICIAL_NAME} mantém uma lista de ativos permitidos e proíbe tecnologias que aprimoram o anonimato (mixers, tumblers, certas moedas/tokens). Qualquer uso detectado dessas tecnologias resulta em banimento.`,
          `• Gestão de Fornecedores: A ${VITE_OFFICIAL_NAME} estabelece parcerias com fornecedores de serviços terceirizados de renome como parte de sua infraestrutura de conformidade. Os principais fornecedores são avaliados regularmente para garantir que os serviços atendam às obrigações contratuais e, se necessário, medidas corretivas são tomadas. Os fornecedores podem ser solicitados a fornecer informações como parte do processo de avaliação.`,
          `• Inovação em Conformidade: Além da gestão de fornecedores, a ${VITE_OFFICIAL_NAME} monitora soluções emergentes de conformidade para avaliar sua aplicabilidade. Programas piloto podem ser conduzidos para avaliar a eficácia. As ferramentas nativas de blockchain incluem serviços antifraude, provedores de KYC on-chain e outras ferramentas que refletem as características técnicas das plataformas blockchain.`,
          `• Educação e Treinamento: Sob a supervisão do departamento jurídico e do diretor de compliance, a ${VITE_OFFICIAL_NAME} oferece treinamento regular em AML, CFT e conformidade com sanções aos funcionários, conforme necessário.`,
          `• Relatórios: A ${VITE_OFFICIAL_NAME} é obrigada por lei a reportar quaisquer transações incomuns ou suspeitas. Clientes confirmados em listas de sanções ou envolvidos em lavagem de dinheiro, financiamento do terrorismo ou outras atividades criminosas são reportados às autoridades reguladoras como atividades suspeitas.`,
        ],
      },
    ],
  },
  'zh-CN': {
    title: '反洗钱和反恐融资声明',
    sections: [
      {
        heading: '1. 公司业务模式',
        paragraphs: [
          `${VITE_OFFICIAL_NAME}成立于2017年，目前在全球支持超过169个国家的用户。`,
          `作为其全球运营的一部分，${VITE_OFFICIAL_NAME}已建立与其服务和产品相符的合规措施，合理设计以防范和检测平台上的非法活动。`,
          '这些措施包括客户入职与合规筛查，以及基于交易行为的控制。',
        ],
      },
      {
        heading: '2. 公司政策声明',
        paragraphs: [
          `${VITE_OFFICIAL_NAME}不是库拉索法律规定意义上的金融机构，因此不直接受到适用于某些金融机构、汇款或虚拟资产服务提供商的法规约束。`,
          `根据库拉索游戏监管委员会针对库拉索司法辖区发布的2016年反洗钱与打击恐怖融资（“AML/CFT”）规定，${VITE_OFFICIAL_NAME}明确禁止并拒绝将其产品用于任何非法活动，包括洗钱、恐怖融资或违反贸易制裁；并遵守各国AML法律、法规与规范。`,
          `${VITE_OFFICIAL_NAME}持续监控由金融行动工作组（FATF）、相关游戏行业团体及库拉索游戏监管委员会制定的标准，并将依据法律变化采取必要措施。`,
          `${VITE_OFFICIAL_NAME}旨在遵循全球最佳实践，防止其产品被用于促成上述活动。最佳实践包括：`,
          '— 采用书面政策、程序与控制，合理设计以防范洗钱、恐怖融资与违反贸易制裁；',
          '— 在适当情况下指定合规主管（Compliance Officer）监督政策、程序与控制的实施；',
          '— 为相关人员提供教育与培训；',
          '— 对政策、程序与控制进行独立审查、持续监控与维护。',
        ],
      },
      {
        heading: '3. 定义',
        paragraphs: [
          '洗钱：使非法获得的收益看起来合法的过程，通常分为三个步骤：入账（Placement）、分层（Layering）与整合（Integration）。',
          '入账：将非法获得的收益通过存款或其他途径存入传统金融机构。',
          '分层：通过复杂金融交易（如将现金转换为旅行支票、汇票、电汇、信用证、股票、债券或购买资产）将犯罪收益与其来源分离。',
          '整合：使用表面合法的交易掩盖非法收益，使洗净资金重新进入正常使用。',
          '可疑活动：由用户或非用户进行的交易，存在迹象表明可能出于欺诈或非法目的。',
          '制裁：国际社会为禁止或限制特定活动而采取的措施，例如：鼓励目标国/政权改变行为；对目标国施压以遵守既定目标；在国际和平与安全受威胁且外交努力失败时作为执法手段；防止和遏制恐怖主义或恐怖行为的资金。',
        ],
      },
      {
        heading: '4. 治理和监督',
        paragraphs: [
          `${VITE_OFFICIAL_NAME}已任命首席合规官（Chief Compliance Officer，“CCO”），负责协调AML政策与项目实施。`,
          'CCO职责包括：制定AML计划、与相关方更新AML政策、评估新监管要求、调查潜在可疑或异常活动。',
          `${VITE_OFFICIAL_NAME}为全体员工定期提供AML培训。`,
        ],
      },
      {
        heading: '5. 了解您的客户（KYC）与交易监控',
        paragraphs: [
          `${VITE_OFFICIAL_NAME}实施法律要求的适当用户尽职调查（DD）与持续监控措施，致力于防止用户从事非法或未经授权的活动；通过软件功能与服务协议的组合以确保遵法合规。`,
          'A. 客户尽职调查（CDD）：采用基于风险的方法，理解用户与平台关系的性质与目的，形成客户风险画像。开户时按账户类型与服务性质收集相关书面与非书面信息，并为不同账户/服务维持不同的CDD要求。',
          '— 顾客识别程序（CIP）示例：在账户创建时通过入职门户收集基线信息（如钱包地址、邮箱）；监控为账户注资的加密钱包的风险画像；记录用于识别用户的信息；核对用户是否出现在金融机构提供的已知或疑似恐怖分子名单中。',
          '— 实施手段：身份与年龄验证（第三方核验KYC资料的有效性、合法资格与非受全面制裁/禁止辖区）；利用入职信息（如钱包地址）核对全球制裁名单。',
          '— 客户信息：为形成对用户身份的合理信念，按风险画像收集细节（钱包地址、姓名、地址、国家、出生日期、邮编等，统称“KYC信息”）；在发放资金地址（如二维码）前收集；当前不接受非自然人用户；可依赖其他机构执行部分/全部CIP要素。',
          '— 地理阻断：合同客户须证明不在被禁止的国家；通过IP地理阻断验证；不得为美国、欧盟或其他全球制裁/观察名单的对象，包括美国全面制裁辖区（伊朗、古巴、朝鲜、叙利亚、克里米亚）相关个人或实体；通过KYC与IP地理阻断等基于风险的措施加以验证。',
          `— 合同禁止从受限辖区引入用户，并告知该等地区不提供服务；相关政策基于${VITE_OFFICIAL_NAME}风险、反欺诈与AML标准及服务可提供性的评估。`,
          'B. 增强的尽职调查（EDD）与持续监控：持续监控用户以发现与洗钱/恐怖融资相关的行为或指标；红旗指标触发时，账户暂停并开展EDD，可能要求并核验：全名、国籍、永久地址、身份证件号码（税号/护照号及签发国/外侨证等）、身份文件、资金与财富来源；必要时通过第三方核验以合理确认真实身份。',
          `C. 受理政策：以下情形不接受并予以封锁——未提供所需身份信息、提交虚假证件、试图伪装位置、来自受限/禁止辖区、受美欧或其他全球制裁/观察名单约束、长期赌博成瘾或精神健康问题、在受限辖区交易或使用被禁止的资金来源；${VITE_OFFICIAL_NAME}保留基于其他原因封锁/暂停的权利。`,
          '交易监控：严格遵守经营辖区的经济与贸易制裁；建立交易监控计划，结合自研规则系统与第三方系统以实现实时与持续异常识别；通过员工/客户身份核验、执法查询、外部推荐、交易与监控系统报告等识别异常，并对已识别或潜在可疑活动进行调查、评估与记录。',
          '— 制裁与受限辖区交易监控：监控来自制裁/禁止辖区的交易；在余额提取时可施加额外尽调；手动+自动监控识别红旗；可拒绝可疑提现或向收款方索取更多信息；限制试图从被禁止辖区为账户注资的用户（该等辖区在UI披露并内部更新），例如可能禁止使用与美国交易所相关的钱包为账户注资；用户可按持续监控与KYC标准提供补充信息以申诉暂停。',
          '— 制裁筛查：在发放资金地址前，使用第三方区块链取证供应商（如Chainalysis）将钱包地址与适用制裁数据库比对；并定期复筛。',
          '— 可疑活动识别：按交易规模、频率、模式与类型并结合风险因素与红旗进行监控，定期生成异常/高风险/可疑活动报告。',
          '— 反混合（Anti-Mixing）措施：通过软件检测可疑充值/提现模式；按风险逐案处理，并可要求说明平台使用方式与目的。',
          '— Chainalysis审核：对所有加密充值与提现（直接/间接）审查欺诈或可疑迹象；对高风险账户可要求资金来源证明；依据风险评分可拒绝向“高风险”地址提现。',
          '— 提款门槛KYC：不论地域或关联，只要账户在其风险特征下达到提款门槛，即暂停至完成充分KYC尽调。',
          '其他持续监控控制：多账户检测（第三方软件关联同设备登录的账户；平台内P2P转账禁止，规避视为红旗）；时区监控（交叉核对受限辖区以发现借助地理定位工具隐藏来源的企图）；产品与服务审查（限制可上传资产、维护可用资产清单、禁止混币器/搅拌器/特定币种等匿名增强技术并一经发现即禁止）；',
          '供应商管理：与信誉良好的第三方服务商合作，定期评估其履约情况并在必要时采取补救措施；供应商可能需在审查过程中提供信息。',
          '合规创新：持续监测新兴合规方案并开展小规模试点以评估效果；区块链原生工具包括反欺诈服务、链上KYC等，符合区块链平台技术特性。',
          '教育与培训：在法律顾问协助与CCO监督下，按需为员工提供AML、CFT与制裁合规的定期培训。',
          `报告：依据国家法律，${VITE_OFFICIAL_NAME}有义务报告任何异常或可疑交易；被列入制裁名单或涉及洗钱、恐怖融资或其他犯罪活动的客户将作为可疑活动报送监管机构。`,
        ],
      },
    ],
  },
  'ko-KR': {
    title: '자금세탁방지 및 테러자금조달 방지 성명서',
    sections: [
      {
        heading: '1. 사업 모델',
        paragraphs: [
          `${VITE_OFFICIAL_NAME}는 2017년에 설립되었으며 현재 전 세계 169개국 이상의 사용자들을 지원하고 있습니다.`,
          `글로벌 운영의 일환으로, ${VITE_OFFICIAL_NAME}는 자사 서비스와 제품에 부합하는 준수 조치를 시행하여 플랫폼에서 불법 활동을 합리적으로 방지하고 감지하도록 설계했습니다.`,
          '이러한 조치에는 고객 온보딩 및 준수 심사뿐만 아니라 거래 기반 통제도 포함됩니다.',
        ],
      },
      {
        heading: '2. 회사 정책 성명서',
        paragraphs: [
          `${VITE_OFFICIAL_NAME}는 큐라소(Curaçao) 법상 금융기관이 아니므로 특정 금융기관, 송금업체 또는 가상자산 서비스 제공업체에 적용되는 규제를 직접적으로 받지 않습니다.`,
          `그러나 큐라소 관할권에 대한 큐라소 게임 통제위원회(Curaçao Gaming Control Board)가 제공한 2016년 자금세탁방지 및 테러자금조달 방지(“AML/CFT”) 규정에 따라, ${VITE_OFFICIAL_NAME}는 자사 제품이 자금세탁, 테러자금조달 또는 무역 제재 위반을 포함한 불법 활동에 사용되는 것을 엄격히 금지하고 거부하며, 각국의 AML 법률, 규제 및 기준에 따라 운영됩니다.`,
          `${VITE_OFFICIAL_NAME}는 금융행동기구(FATF), 관련 게임 산업 기관, 큐라소 게임 통제위원회가 설정한 기준을 지속적으로 모니터링하며, 법률 변경에 따라 필요한 조치를 취합니다.`,
          `${VITE_OFFICIAL_NAME}는 자사 제품이 이러한 활동을 촉진하는 데 사용되지 않도록 글로벌 모범 사례를 준수하는 것을 목표로 합니다.`,
          '이러한 모범 사례에는 다음이 포함됩니다:',
          '• 자금세탁, 테러자금조달 및 무역 제재 위반을 방지하도록 합리적으로 설계된 서면 정책, 절차 및 통제 시행;',
          '• 필요 시 정책, 절차 및 통제를 감독할 준법감시 책임자(Compliance Officer) 임명;',
          '• 관련 교육 및 훈련 제공;',
          '• 정책, 절차 및 통제의 독립적 검토, 모니터링 및 유지 수행.',
        ],
      },
      {
        heading: '3. 정의',
        paragraphs: [
          '• 자금세탁(Money Laundering): 불법적으로 취득한 자금을 합법적으로 보이도록 만드는 과정으로, 일반적으로 세 단계로 구성됩니다: 배치(Placement), 층화(Layering), 통합(Integration).',
          '• 배치(Placement): 불법적으로 취득한 자금을 예금 등 방식으로 전통적 금융기관에 예치하는 것.',
          '• 층화(Layering): 복잡한 금융 거래를 통해 범죄 수익을 출처와 분리하는 것.',
          '• 통합(Integration): 합법적으로 보이는 거래를 이용하여 세탁된 자금을 정상적으로 사용하는 것.',
          '• 의심 활동(Suspicious Activity): 사용자 또는 비사용자의 거래가 사기 또는 불법 목적을 위해 수행될 수 있음을 나타내는 경우.',
          '• 제재(Sanctions): 국제 사회가 특정 활동을 금지하거나 제한하기 위해 부과하는 조치. 예를 들어, 대상 국가 또는 정권의 행동 변경 유도, 국제 평화와 안보 유지, 테러자금조달 방지 등.',
        ],
      },
      {
        heading: '4. 거버넌스 및 감독',
        paragraphs: [
          `${VITE_OFFICIAL_NAME}는 AML 정책과 프로그램 실행을 조율할 최고 준법감시 책임자(CCO)를 임명했습니다.`,
          'CCO의 업무에는 AML 프로그램 개발, 정책 업데이트, 신규 규제 요건 평가, 잠재적 의심 또는 비정상 활동 조사 등이 포함됩니다.',
          `또한 ${VITE_OFFICIAL_NAME}는 모든 직원에게 정기적인 AML 교육을 제공합니다.`,
        ],
      },
      {
        heading: '5. 고객 확인(KYC) 및 거래 모니터링',
        paragraphs: [
          `${VITE_OFFICIAL_NAME}는 법적으로 요구되는 사용자 실사 및 지속적인 모니터링 조치를 적용합니다.`,
          '고객 확인(KYC)에는 CDD(고객 실사), EDD(강화된 실사), 수용 정책이 포함됩니다.',
          'A. 고객 실사(CDD): 위험 기반 접근 방식을 통해 사용자의 위험 프로필을 작성하고 계정 개설 시 정보(지갑 주소, 이메일 등)를 수집합니다.',
          '• 신원 및 연령 확인: 제3자 제공업체가 신원 유효성을 검증하고 제재 여부를 확인합니다.',
          '• 고객 정보: 지갑 주소, 이름, 주소, 국가, 생년월일 등 상세 정보 수집.',
          '• 금지된 관할권 지오블로킹: IP 기반 검증을 통해 금지 국가 접근 차단.',
          'B. 강화된 실사(EDD): 레드플래그가 감지되면 계정을 중단하고 추가 정보(이름, 주소, 신분증 등)를 요청합니다.',
          'C. 수용 정책: 허위 신원, 금지 국가, 제재 대상자 등은 차단됩니다.',
          `거래 모니터링: ${VITE_OFFICIAL_NAME}는 경제 및 무역 제재를 준수하며, 자체 및 제3자 시스템으로 거래를 실시간 감시합니다.`,
          '• 제재 및 제한 관할권 모니터링;',
          '• 제재 심사 및 블록체인 포렌식;',
          '• 의심 활동 탐지 및 혼합 방지;',
          '• Chainalysis 기반 검토;',
          '• 인출 기준 KYC;',
          '추가 지속 모니터링 통제에는 다중 계정 탐지, 시간대 모니터링, 제품 및 서비스 검토, 벤더 관리, 준수 혁신, 교육 및 훈련, 의심 거래 보고가 포함됩니다.',
        ],
      },
    ],
  },
  'hi-IN': {
    title: 'मनी लॉन्ड्रिंग और आतंकवाद वित्तपोषण विरोधी बयान',
    sections: [
      {
        heading: '1. व्यवसाय मॉडल',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} की स्थापना 2017 में हुई थी और वर्तमान में यह दुनिया के 169 से अधिक देशों में उपयोगकर्ताओं का समर्थन करता है।`,
          `अपने वैश्विक संचालन के हिस्से के रूप में, ${VITE_OFFICIAL_NAME} ने अपनी सेवाओं और उत्पादों के अनुरूप अनुपालन उपाय लागू किए हैं, जो प्लेटफ़ॉर्म पर अवैध गतिविधियों को रोकने और पहचानने के लिए तर्कसंगत रूप से डिज़ाइन किए गए हैं।`,
          'इन उपायों में ग्राहक ऑनबोर्डिंग और अनुपालन स्क्रीनिंग के साथ-साथ लेनदेन-आधारित नियंत्रण शामिल हैं।',
        ],
      },
      {
        heading: '2. कंपनी नीति बयान',
        paragraphs: [
          `${VITE_OFFICIAL_NAME}, कुराकाओ कानून के तहत एक वित्तीय संस्थान नहीं है और इसलिए यह कुछ वित्तीय संस्थानों, प्रेषण प्रदाताओं या वर्चुअल एसेट सेवा प्रदाताओं पर लागू नियमों के प्रत्यक्ष अधीन नहीं है।`,
          `हालांकि, 2016 के एंटी-मनी लॉन्ड्रिंग और काउंटर-टेररिज़्म फाइनेंसिंग (AML/CFT) नियमों के तहत, जो कुराकाओ जूरीस्डिक्शन के लिए कुराकाओ गेमिंग कंट्रोल बोर्ड द्वारा प्रदान किए गए हैं, ${VITE_OFFICIAL_NAME} अपने उत्पादों के किसी भी अवैध उपयोग को सख्ती से निषिद्ध और अस्वीकार करता है।`,
          'यह विभिन्न देशों के AML कानूनों, नियमों और मानकों के अनुरूप संचालित होता है।',
          `${VITE_OFFICIAL_NAME} फाइनेंशियल एक्शन टास्क फोर्स (FATF), संबंधित गेमिंग उद्योग निकायों और कुराकाओ गेमिंग कंट्रोल बोर्ड द्वारा निर्धारित मानकों की लगातार निगरानी करता है और कानूनी परिवर्तनों के जवाब में आवश्यक कार्रवाई करता है।`,
          `${VITE_OFFICIAL_NAME} का उद्देश्य वैश्विक सर्वोत्तम प्रथाओं का पालन करना है ताकि उसके उत्पादों का उपयोग अवैध गतिविधियों को सुविधाजनक बनाने के लिए न किया जा सके।`,
          'इन सर्वोत्तम प्रथाओं में शामिल हैं:',
          '• मनी लॉन्ड्रिंग, आतंकवाद वित्तपोषण और व्यापार प्रतिबंधों के उल्लंघन को रोकने के लिए लिखित नीतियाँ, प्रक्रियाएँ और नियंत्रण लागू करना;',
          '• उपयुक्त होने पर नीतियों और नियंत्रणों की निगरानी के लिए एक अनुपालन अधिकारी (Compliance Officer) नियुक्त करना;',
          '• कर्मचारियों को प्रासंगिक शिक्षा और प्रशिक्षण प्रदान करना;',
          '• नीतियों और नियंत्रणों की स्वतंत्र समीक्षा, निगरानी और रखरखाव करना।',
        ],
      },
      {
        heading: '3. परिभाषाएँ',
        paragraphs: [
          'मनी लॉन्ड्रिंग: अवैध रूप से प्राप्त धन को वैध दिखाने की प्रक्रिया, आमतौर पर तीन चरणों में: प्लेसमेंट, लेयरिंग और इंटीग्रेशन।',
          'प्लेसमेंट: अवैध रूप से प्राप्त धन को जमा या अन्य तरीकों से पारंपरिक वित्तीय संस्थानों में जमा करना।',
          'लेयरिंग: जटिल वित्तीय लेनदेन के माध्यम से आपराधिक आय को उनके स्रोत से अलग करना।',
          'इंटीग्रेशन: वैध दिखने वाले लेनदेन का उपयोग करके अवैध रूप से प्राप्त धन को छुपाना, जिससे इसे सामान्य उपयोग में लाया जा सके।',
          'संदिग्ध गतिविधि: लेनदेन जो संकेत देती है कि वह धोखाधड़ीपूर्ण या अवैध उद्देश्यों के लिए किया जा सकता है।',
          'प्रतिबंध: अंतरराष्ट्रीय समुदाय द्वारा लगाए गए उपाय जो प्रतिबंधित गतिविधियों को रोकने या सीमित करने के लिए होते हैं, जैसे:',
          '• लक्षित देश या शासन को व्यवहार बदलने के लिए प्रोत्साहित करना;',
          '• लक्षित देश पर निर्धारित उद्देश्यों का पालन करने के लिए दबाव डालना;',
          '• अंतरराष्ट्रीय शांति और सुरक्षा के खतरे में होने पर प्रवर्तन उपकरण के रूप में उपयोग करना;',
          '• आतंकवादियों या आतंकवादी कृत्यों के वित्तपोषण को रोकना और दबाना।',
        ],
      },
      {
        heading: '4. शासन और निरीक्षण',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} ने एक मुख्य अनुपालन अधिकारी (CCO) नियुक्त किया है, जो AML नीतियों और कार्यक्रम के कार्यान्वयन का समन्वय करने के लिए जिम्मेदार है।`,
          'CCO के कर्तव्यों में AML प्रोग्राम का विकास, हितधारकों के साथ नीति अद्यतन, नियामक आवश्यकताओं का मूल्यांकन और संदिग्ध गतिविधियों की जांच शामिल है।',
          `${VITE_OFFICIAL_NAME} सभी कर्मचारियों को नियमित AML प्रशिक्षण भी प्रदान करता है।`,
        ],
      },
      {
        heading: '5. अपने ग्राहक को जानें (KYC) और लेनदेन निगरानी',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} कानूनी रूप से आवश्यक उपयोगकर्ता परिश्रम (due diligence) और सतत निगरानी उपाय लागू करता है ताकि अवैध या अनधिकृत गतिविधियों को रोका जा सके।`,
          `A. ग्राहक परिश्रम (CDD): जोखिम-आधारित दृष्टिकोण अपनाते हुए ${VITE_OFFICIAL_NAME} उपयोगकर्ताओं की पहचान करता है, उनकी जोखिम प्रोफ़ाइल बनाता है और संबंधित जानकारी (वॉलेट पता, ईमेल, आदि) एकत्र करता है।`,
          '• पहचान और आयु सत्यापन: तृतीय-पक्ष प्रदाताओं द्वारा पहचान जानकारी की वैधता की पुष्टि की जाती है।',
          '• ग्राहक जानकारी: नाम, पता, देश, जन्म तिथि और वॉलेट पते जैसी जानकारी एकत्र की जाती है।',
          '• प्रतिबंधित क्षेत्रों के लिए भू-निषेध: IP आधारित geoblocking के माध्यम से निषिद्ध देशों से एक्सेस को रोका जाता है।',
          'B. उन्नत परिश्रम और सतत निगरानी (EDD): लाल झंडा संकेतकों के आधार पर खातों की निगरानी की जाती है, संदिग्ध व्यवहार पाए जाने पर खाते निलंबित किए जाते हैं और अतिरिक्त जानकारी मांगी जाती है।',
          `C. स्वीकृति नीति: ${VITE_OFFICIAL_NAME} झूठे दस्तावेज़, निषिद्ध क्षेत्रों के उपयोगकर्ता, या प्रतिबंध सूची में शामिल किसी भी व्यक्ति को स्वीकार नहीं करता।`,
          `लेनदेन निगरानी: ${VITE_OFFICIAL_NAME} आर्थिक और व्यापारिक प्रतिबंधों का पालन करता है और नियम-आधारित तथा तृतीय-पक्ष प्रणालियों के संयोजन से लेनदेन की निगरानी करता है।`,
          '• प्रतिबंधित क्षेत्रों और प्रतिबंध सूची की निगरानी;',
          '• Chainalysis जैसी सेवाओं के माध्यम से वॉलेट पतों की स्क्रीनिंग;',
          '• संदिग्ध गतिविधि की पहचान और रिपोर्टिंग;',
          '• मिश्रण विरोधी उपायों का कार्यान्वयन;',
          '• उच्च जोखिम खातों की समीक्षा और KYC सत्यापन;',
          'अतिरिक्त सतत निगरानी नियंत्रण: मल्टीपल अकाउंट डिटेक्शन, टाइमज़ोन मॉनिटरिंग, उत्पाद और सेवा समीक्षा, वेंडर प्रबंधन, अनुपालन नवाचार, शिक्षा और प्रशिक्षण, और संदिग्ध लेनदेन की रिपोर्टिंग शामिल हैं।',
        ],
      },
    ],
  },
  'in-ID': {
    title: 'Pernyataan Anti-Pencucian Uang & Pencegahan Pendanaan Terorisme',
    sections: [
      {
        heading: '1. Model Bisnis',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} didirikan pada tahun 2017 dan saat ini mendukung pengguna di lebih dari 169 negara di seluruh dunia.`,
          `Sebagai bagian dari operasi globalnya, ${VITE_OFFICIAL_NAME} telah menerapkan langkah-langkah kepatuhan yang selaras dengan layanan dan produknya, yang dirancang untuk secara wajar mencegah dan mendeteksi aktivitas ilegal di platformnya.`,
          'Langkah-langkah ini mencakup onboarding pelanggan dan skrining kepatuhan, serta kontrol berbasis transaksi.',
        ],
      },
      {
        heading: '2. Pernyataan Kebijakan Perusahaan',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} bukanlah lembaga keuangan berdasarkan hukum Curaçao dan oleh karena itu tidak secara langsung tunduk pada regulasi yang berlaku untuk lembaga keuangan tertentu, penyedia remitansi, atau penyedia layanan aset virtual.`,
          `Namun, berdasarkan aturan Anti-Pencucian Uang dan Pencegahan Pendanaan Terorisme ("AML/CFT") 2016 yang diberikan oleh Curaçao Gaming Control Board untuk yurisdiksi Curaçao, ${VITE_OFFICIAL_NAME} secara tegas melarang dan menolak penggunaan produknya untuk kegiatan ilegal apa pun, termasuk pencucian uang, pendanaan terorisme, atau pelanggaran sanksi perdagangan, sesuai dengan hukum, regulasi, dan standar AML di berbagai negara.`,
          `${VITE_OFFICIAL_NAME} secara terus-menerus memantau standar yang ditetapkan oleh Financial Action Task Force ("FATF"), badan industri permainan yang relevan, dan Curaçao Gaming Control Board, dan akan mengambil tindakan yang diperlukan sebagai respons terhadap perubahan hukum.`,
          `${VITE_OFFICIAL_NAME} bertujuan mengikuti praktik terbaik global untuk mencegah produknya digunakan untuk memfasilitasi aktivitas tersebut.`,
          'Praktik terbaik ini mencakup:',
          '• Menerapkan kebijakan, prosedur, dan kontrol tertulis yang secara wajar dirancang untuk mencegah pencucian uang, pendanaan terorisme, dan pelanggaran sanksi perdagangan;',
          '• Menunjuk Petugas Kepatuhan (Compliance Officer), bila diperlukan, untuk mengawasi pelaksanaan kebijakan, prosedur, dan kontrol;',
          '• Menyediakan pendidikan dan pelatihan yang relevan kepada personel; dan',
          '• Melakukan tinjauan independen, pemantauan, dan pemeliharaan kebijakan, prosedur, dan kontrol.',
        ],
      },
      {
        heading: '3. Definisi',
        paragraphs: [
          'Istilah-istilah berikut banyak digunakan dalam industri:',
          'Pencucian Uang: Proses membuat dana yang diperoleh secara ilegal tampak sah, biasanya melalui tiga tahap: penempatan, pelapisan, dan integrasi.',
          'Penempatan (Placement): Menyimpan dana yang diperoleh secara ilegal ke lembaga keuangan tradisional melalui setoran atau cara lain.',
          'Pelapisan (Layering): Memisahkan hasil kriminal dari sumbernya melalui transaksi keuangan yang kompleks, seperti mengubah uang tunai menjadi cek perjalanan, wesel, transfer kawat, surat kredit, saham, obligasi, atau membeli aset.',
          'Integrasi (Integration): Menggunakan transaksi yang tampaknya sah untuk menyamarkan dana yang diperoleh secara ilegal, memungkinkan dana yang dicuci kembali digunakan secara normal oleh pelaku kriminal.',
          'Aktivitas Mencurigakan (Suspicious Activity): Transaksi oleh pengguna atau non-pengguna yang menunjukkan transaksi tersebut mungkin dilakukan untuk tujuan penipuan atau ilegal.',
          'Sanksi (Sanctions): Tindakan yang diberlakukan oleh komunitas internasional untuk melarang atau membatasi kegiatan yang dikenai sanksi, misalnya:',
          '• Mendorong negara atau rezim target mengubah perilakunya;',
          '• Menerapkan tekanan pada negara target agar mematuhi tujuan yang ditetapkan;',
          '• Menjadi alat penegakan ketika perdamaian dan keamanan internasional terancam dan upaya diplomatik gagal;',
          '• Mencegah dan menekan pendanaan teroris atau tindakan teroris.',
        ],
      },
      {
        heading: '4. Tata Kelola & Pengawasan',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} telah menunjuk Chief Compliance Officer ("CCO") yang bertanggung jawab untuk mengoordinasikan kebijakan AML dan implementasi program.`,
          `Tugas CCO mencakup mengembangkan program AML, memperbarui kebijakan AML bersama pemangku kepentingan ${VITE_OFFICIAL_NAME} lainnya, mengevaluasi persyaratan regulasi baru, dan menyelidiki aktivitas yang berpotensi mencurigakan atau tidak biasa.`,
          `${VITE_OFFICIAL_NAME} juga menyediakan pelatihan AML secara rutin untuk semua karyawan.`,
        ],
      },
      {
        heading: '5. Kenali Pelanggan Anda (KYC) & Pemantauan Transaksi',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} menerapkan tindakan uji tuntas pengguna yang diwajibkan secara hukum serta langkah-langkah pemantauan berkelanjutan untuk mencegah aktivitas ilegal atau tidak sah.`,
          `A. Customer Due Diligence (CDD): ${VITE_OFFICIAL_NAME} menggunakan pendekatan berbasis risiko untuk memahami hubungan pengguna–platform dan menyusun profil risiko tiap pelanggan; selama pendaftaran, ${VITE_OFFICIAL_NAME} mengumpulkan informasi tertulis dan non-tertulis yang relevan (mis. alamat dompet, email), dan menerapkan CDD berbeda per jenis akun/layanan.`,
          '• Verifikasi Identitas & Usia: Penyedia pihak ketiga memverifikasi keabsahan informasi identitas dan materi KYC, memastikan pengguna diizinkan secara hukum dan tidak berada di yurisdiksi yang sepenuhnya disanksi atau dilarang; daftar sanksi global diperiksa menggunakan data onboarding seperti alamat dompet.',
          `• Informasi Pelanggan: ${VITE_OFFICIAL_NAME} mengumpulkan detail (alamat dompet, nama, alamat, negara, tanggal lahir, kode pos) untuk membentuk keyakinan yang wajar atas identitas pengguna sebelum menerbitkan alamat pendanaan (mis. kode QR); saat ini pengguna non-alami tidak diperbolehkan; sebagian/seluruh elemen CIP dapat diandalkan pada entitas lain.`,
          '• Geoblocking untuk Yurisdiksi Terlarang: Pengguna mengonfirmasi tidak berada di negara terlarang; diverifikasi melalui geoblocking berbasis IP; pengguna tidak boleh menjadi subjek sanksi/watched lists AS, UE, atau global (termasuk Iran, Kuba, Korea Utara, Suriah, dan Crimea).',
          `Kontrak melarang onboarding dari yurisdiksi terbatas dan menginformasikan bahwa layanan ${VITE_OFFICIAL_NAME} tidak tersedia di yurisdiksi tersebut; kebijakan didasarkan pada standar risiko, pencegahan penipuan, AML, dan penilaian kelayakan layanan.`,
          `B. Enhanced Due Diligence & Pemantauan Berkelanjutan (EDD): ${VITE_OFFICIAL_NAME} memantau perilaku dan indikator red-flag; bila terpicu, akun dapat ditangguhkan dan dikenai EDD, termasuk pengumpulan/verifikasi nama lengkap, kewarganegaraan, alamat permanen, nomor identifikasi (NPWP/paspor/ID), dokumen identitas, serta sumber dana dan kekayaan; penyedia pihak ketiga dapat digunakan untuk verifikasi.`,
          `C. Kebijakan Penerimaan: ${VITE_OFFICIAL_NAME} tidak menerima dan akan memblokir pengguna yang gagal memberikan data identitas, menyerahkan dokumen palsu, menyembunyikan lokasi, berasal dari yurisdiksi terbatas/terlarang, berada dalam daftar sanksi, memiliki kecanduan judi jangka panjang atau masalah kesehatan mental, atau bertransaksi dari yurisdiksi terbatas/bersumber dana terlarang; ${VITE_OFFICIAL_NAME} berhak melakukan blokir/penangguhan karena alasan lain.`,
          `Pemantauan Transaksi: ${VITE_OFFICIAL_NAME} mematuhi sanksi ekonomi dan perdagangan yang berlaku dan menjalankan program pemantauan transaksi dengan kombinasi sistem berbasis aturan internal dan sistem pihak ketiga untuk identifikasi anomali secara real-time dan berkelanjutan; program mencakup verifikasi identitas, tanggapan atas permintaan penegak hukum, dan pelaporan sistem.`,
          '• Pemantauan Sanksi & Yurisdiksi Terbatas: Transaksi dari wilayah disanksi/terlarang dipantau; uji tuntas tambahan dapat diberlakukan saat penarikan; kombinasi pemantauan manual/otomatis mengidentifikasi red-flag; penarikan mencurigakan dapat ditolak atau diminta info tambahan; pendanaan dari dompet terkait bursa AS dapat diblokir.',
          '• Penyaringan Sanksi: Alamat dompet disaring terhadap database sanksi menggunakan penyedia forensik blockchain pihak ketiga seperti Chainalysis sebelum alamat pendanaan diterbitkan; dompet diperiksa ulang berkala.',
          '• Deteksi Aktivitas Mencurigakan: Aktivitas akun dipantau untuk ukuran, frekuensi, pola, atau jenis transaksi yang tidak biasa dengan mempertimbangkan faktor risiko dan red-flag; laporan aktivitas tidak biasa/berisiko tinggi/mencurigakan dibuat secara rutin.',
          '• Langkah Anti-Mixing: Perangkat lunak mendeteksi pola setoran/penarikan mencurigakan; kasus ditinjau berbasis risiko; pengguna dapat diminta menjelaskan penggunaan platform.',
          '• Tinjauan Chainalysis: Semua setoran/penarikan kripto, langsung maupun tidak langsung, ditinjau untuk indikasi penipuan atau aktivitas mencurigakan; akun berisiko tinggi dapat diminta bukti sumber dana; penarikan ke alamat berisiko tinggi berdasarkan skor Chainalysis dapat ditolak.',
          '• KYC Ambang Penarikan: Akun yang mencapai ambang penarikan sesuai profil risiko ditangguhkan sampai uji tuntas KYC memadai selesai.',
          'Kontrol Pemantauan Berkelanjutan Tambahan: Deteksi multi-akun; pemantauan zona waktu dan pencocokan dengan yurisdiksi terbatas; tinjauan produk & layanan dan kebijakan pembatasan aset unggahan; manajemen vendor dan evaluasi berkala; inovasi kepatuhan termasuk pilot tools native blockchain (anti-fraud, on-chain KYC); pendidikan & pelatihan AML/CFT & sanksi; serta pelaporan transaksi tidak biasa atau mencurigakan kepada otoritas.',
        ],
      },
    ],
  },
  'ja-JP': {
    title: 'マネーロンダリング防止およびテロ資金供与対策（AML/CFT）声明',
    sections: [
      {
        heading: '1. ビジネスモデル',
        paragraphs: [
          `${VITE_OFFICIAL_NAME}は2017年に設立され、現在169か国以上のユーザーをサポートしています。`,
          `グローバル事業の一環として、${VITE_OFFICIAL_NAME}はサービスおよび製品に適合したコンプライアンス措置を実施しており、プラットフォーム上での違法行為を合理的に防止・検出することを目的としています。`,
          'これらの措置には、顧客のオンボーディングおよびコンプライアンススクリーニング、取引ベースの管理が含まれます。',
        ],
      },
      {
        heading: '2. 会社方針声明',
        paragraphs: [
          `${VITE_OFFICIAL_NAME}はキュラソー法上の金融機関ではないため、特定の金融機関、送金業者、または仮想資産サービス提供者に適用される規制の対象には直接はなりません。`,
          `しかしながら、キュラソーゲーム管理委員会が提供する2016年のAML/CFT規則に基づき、${VITE_OFFICIAL_NAME}はマネーロンダリング、テロ資金供与、貿易制裁違反を含むあらゆる違法行為に対して、自社製品の使用を厳格に禁止し、拒否します。これは、各国のAML関連法規、規制および基準に従ったものです。`,
          `${VITE_OFFICIAL_NAME}は、金融活動作業部会（FATF）、関連するゲーム業界団体、キュラソーゲーム管理委員会によって定められた基準を継続的に監視し、法改正に応じて必要な措置を講じます。`,
          `${VITE_OFFICIAL_NAME}は、自社製品が違法活動の助長に利用されることを防ぐため、グローバルなベストプラクティスに従うことを目指しています。`,
          'これらのベストプラクティスには以下が含まれます：',
          '• マネーロンダリング、防テロ資金供与、および貿易制裁違反を防止するために合理的に設計された文書化された方針、手順、および管理策の実施;',
          '• 適切な場合、方針、手順、および管理策の実施を監督するコンプライアンス責任者（Compliance Officer）の任命;',
          '• 関連する教育および研修の提供;',
          '• 方針、手順、および管理策の独立したレビュー、モニタリング、維持。',
        ],
      },
      {
        heading: '3. 定義',
        paragraphs: [
          '• マネーロンダリング（Money Laundering）：不正に取得した資金を合法的に見せかけるプロセスで、通常は「配置（Placement）」「層化（Layering）」「統合（Integration）」の3段階で行われます。',
          '• 配置（Placement）：不正に取得した資金を預金やその他の手段で従来の金融機関に預け入れること。',
          '• 層化（Layering）：現金をトラベラーズチェック、マネーオーダー、送金、信用状、株式、債券などに変換するなど、複雑な金融取引を通じて犯罪収益をその出所から切り離すこと。',
          '• 統合（Integration）：一見合法的な取引を使用して不正資金を隠蔽し、洗浄された資金を犯罪者が通常の使用に再投入できるようにすること。',
          '• 疑わしい活動（Suspicious Activity）：ユーザーまたは非ユーザーによる、詐欺または違法目的で行われる可能性のある交易。',
          '• 制裁（Sanctions）：国際社会が制裁対象活動を禁止または制限するために課す措置。例えば、以下の目的で使用されます：',
          '  • 対象国または政権に行動の変更を促す;',
          '  • 対象国に目標達成のための圧力をかける;',
          '  • 国際平和と安全が脅かされ、外交努力が失敗した場合の執行手段として利用;',
          '  • テロリストやテロ行為の資金調達を防止・抑制する。',
        ],
      },
      {
        heading: '4. ガバナンスおよび監督',
        paragraphs: [
          `${VITE_OFFICIAL_NAME}は、AMLポリシーおよびプログラム実施の調整を担当する最高コンプライアンス責任者（Chief Compliance Officer, “CCO”）を任命しています。`,
          `CCOの職務には、AMLプログラムの開発、他の${VITE_OFFICIAL_NAME}関係者とのAMLポリシーの更新、新規規制要件の評価、および潜在的に疑わしいまたは異常な活動の調査が含まれます。`,
          `また、${VITE_OFFICIAL_NAME}は全従業員に対して定期的にAML研修を提供しています。`,
        ],
      },
      {
        heading: '5. 顧客確認（KYC）および取引モニタリング',
        paragraphs: [
          `${VITE_OFFICIAL_NAME}は、法的に要求されるユーザーのデューデリジェンスおよび継続的なモニタリング措置を適用し、違法または無許可の活動への関与を防止するよう努めています。コンプライアンスは、ソフトウェア機能とサービス契約の組み合わせを通じて適用されます。`,
          'A. 顧客デューデリジェンス（CDD）：リスクベースのアプローチにより関係の性質と目的を把握し、各顧客のリスクプロファイルを作成。登録時にアカウント種別や提供サービスに関連する情報（例：ウォレットアドレス、メール）を収集し、アカウント/サービスごとに異なるCDDを維持。',
          '• 身元および年齢確認：第三者提供者がKYC資料の有効性を確認し、完全制裁または禁止管轄に該当しないことを検証。オンボーディング情報（ウォレットアドレス等）でグローバル制裁リストを照合。',
          '• 顧客情報：ウォレットアドレス、氏名、住所、国、出生年月日、郵便番号等（総称してKYC情報）を資金アドレス発行前に収集。現在、非自然人ユーザーは不可。CIPの一部/全部を他機関に委託する場合あり。',
          '• 制限された管轄区域に対するジオブロッキング：契約ユーザーは禁止国にいないことをIPベースで検証。米国・EU・その他グローバル制裁/監視リストの対象であってはならず、完全制裁対象の米国管轄（イラン、キューバ、北朝鮮、シリア、クリミア）も含む。',
          '契約では、制限管轄からのオンボーディングを禁止し、当該地域でサービスを提供しない旨を通知。方針はリスク管理、詐欺防止、AML基準および提供可能性の評価に基づく。',
          'B. 強化されたデューデリジェンス（EDD）および継続的モニタリング：レッドフラグ指標を用いて監視し、発生時はアカウントを一時停止して追加情報（氏名、国籍、永続的住所、識別番号、身元証明、資金・財産の出所等）を収集・検証。必要に応じ第三者で確認。',
          'C. 受け入れポリシー：要求情報の不提出、虚偽文書、位置偽装、制限/禁止管轄の出自、制裁対象、長期ギャンブル依存や精神健康問題、制限管轄からの取引や禁止資金源の利用は受け入れ不可。その他の理由でもブロック/一時停止の権利を留保。',
          '取引モニタリング：運営管轄の経済・貿易制裁を遵守し、独自ルールベースと第三者システムを組み合わせたプログラムでリアルタイムかつ継続的に異常を検知。従業員・顧客の身元確認、法執行照会、各種レポートを通じ特定し、調査・評価・記録を実施。',
          '• 制裁および制限管轄区域のモニタリング：当該地域からの取引を監視。出金時に追加DDを適用する場合あり。手動/自動の併用でレッドフラグを特定。疑わしい出金は拒否または追加情報を要求。米国取引所関連ウォレットからの資金はブロックされ得る。',
          '• 制裁スクリーニング：資金アドレス発行前にウォレットをChainalysis等の第三者フォレンジックで制裁DBと照合し、定期的に再スクリーニング。',
          '• 疑わしい活動の検出：取引サイズ・頻度・パターン・タイプ等を監視し、リスクとレッドフラグを考慮してレポートを定期作成。',
          '• アンチミキシング措置：疑わしい入出金パターンをソフトウェアで検出。ケースごとにリスク評価し、利用方法の説明を求める場合あり。',
          '• Chainalysisレビュー：全ての暗号資産の入出金（直接・間接）を確認。高リスク口座には資金証明を要求し得る。高リスクアドレスへの出金は拒否され得る。',
          '• 出金閾値KYC：プロファイルに基づく出金閾値到達時は、十分なKYC完了まで一時停止。',
          '追加の継続的モニタリング管理：複数アカウント検出、タイムゾーン監視、製品・サービスレビュー（アップロード資産制限等）、ベンダー管理（定期評価/是正）、コンプライアンス革新（ネイティブブロックチェーンツールのパイロット等）、教育・研修（AML/CFT/制裁）、異常・疑わしい取引の規制当局への報告。',
        ],
      },
    ],
  },
  'th-TH': {
    title: 'นโยบายต่อต้านการฟอกเงินและการสนับสนุนการก่อการร้าย (Anti-Money Laundering & Counter-Terrorism Financing Statement)',
    sections: [
      {
        heading: '1. รูปแบบธุรกิจ (Business Model)',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} ก่อตั้งขึ้นในปี 2017 และปัจจุบันให้บริการผู้ใช้งานในกว่า 169 ประเทศทั่วโลก。`,
          `ในฐานะส่วนหนึ่งของการดำเนินงานระดับโลก ${VITE_OFFICIAL_NAME} ได้ดำเนินมาตรการความสอดคล้องที่สอดคล้องกับบริการและผลิตภัณฑ์ของบริษัท เพื่อป้องกันและตรวจจับกิจกรรมที่ผิดกฎหมายบนแพลตฟอร์มอย่างเหมาะสม。`,
          'มาตรการเหล่านี้รวมถึงการลงทะเบียนลูกค้าและการตรวจสอบความสอดคล้อง ตลอดจนการควบคุมตามธุรกรรม。',
        ],
      },
      {
        heading: '2. คำชี้แจงนโยบายของบริษัท (Company Policy Statement)',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} ไม่ใช่สถาบันการเงินภายใต้กฎหมายของคูราเซา จึงไม่อยู่ภายใต้ข้อบังคับที่ใช้กับสถาบันการเงินบางประเภท ผู้ให้บริการโอนเงิน หรือผู้ให้บริการสินทรัพย์ดิจิทัลโดยตรง。`,
          `อย่างไรก็ตาม ภายใต้กฎ AML/CFT ปี 2016 ที่จัดทำโดย Curaçao Gaming Control Board สำหรับเขตอำนาจคูราเซา ${VITE_OFFICIAL_NAME} ห้ามอย่างเคร่งครัดและปฏิเสธการใช้ผลิตภัณฑ์ของบริษัทสำหรับกิจกรรมที่ผิดกฎหมายใด ๆ รวมถึงการฟอกเงิน การสนับสนุนการก่อการร้าย หรือการละเมิดมาตรการคว่ำบาตร ตามกฎหมาย ระเบียบ และมาตรฐานของหลายประเทศ。`,
          `${VITE_OFFICIAL_NAME} ติดตามมาตรฐานที่กำหนดโดย FATF หน่วยงานอุตสาหกรรมเกมที่เกี่ยวข้อง และ Curaçao Gaming Control Board อย่างต่อเนื่อง และจะดำเนินการตามความจำเป็นเพื่อตอบสนองต่อการเปลี่ยนแปลงทางกฎหมาย。`,
          `${VITE_OFFICIAL_NAME} มีเป้าหมายที่จะปฏิบัติตามแนวทางปฏิบัติที่ดีที่สุดระดับโลกเพื่อป้องกันไม่ให้ผลิตภัณฑ์ของบริษัทถูกใช้ในการสนับสนุนกิจกรรมดังกล่าว。`,
          'แนวทางปฏิบัติที่ดีที่สุดรวมถึง：',
          '• การจัดทำนโยบาย ขั้นตอน และการควบคุมเป็นลายลักษณ์อักษรเพื่อป้องกันการฟอกเงิน การสนับสนุนการก่อการร้าย และการละเมิดมาตรการคว่ำบาตร；',
          '• การแต่งตั้งเจ้าหน้าที่ความสอดคล้อง (Compliance Officer) เมื่อเหมาะสม เพื่อกำกับดูแลการนำมาตรการ นโยบาย และขั้นตอนไปปฏิบัติ；',
          '• การให้การศึกษาและฝึกอบรมที่เกี่ยวข้องกับบุคลากร；',
          '• การตรวจสอบ การติดตาม และบำรุงรักษานโยบาย ขั้นตอน และการควบคุมอย่างอิสระ。',
        ],
      },
      {
        heading: '3. คำจำกัดความ (Definitions)',
        paragraphs: [
          'การฟอกเงิน (Money Laundering): กระบวนการทำให้เงินที่ได้มาโดยผิดกฎหมายดูเหมือนถูกต้องตามกฎหมาย โดยทั่วไปแบ่งเป็น 3 ขั้นตอน: การฝาก (Placement) การแยกชั้น (Layering) และการผสมผสาน (Integration)。',
          'การฝาก (Placement): การนำเงินที่ได้มาโดยผิดกฎหมายไปฝากในสถาบันการเงินแบบดั้งเดิมผ่านการฝากเงินหรือวิธีอื่น ๆ。',
          'การแยกชั้น (Layering): การแยกเงินที่ได้จากอาชญากรรมออกจากแหล่งที่มา ผ่านธุรกรรมทางการเงินที่ซับซ้อน (เช่น เช็คเดินทาง ธนาณัติ โอนเงิน หนังสือเครดิต หุ้น พันธบัตร หรือการซื้อสินทรัพย์)。',
          'การผสมผสาน (Integration): การใช้ธุรกรรมที่ดูเหมือนถูกต้องตามกฎหมายเพื่อปกปิดเงินที่ได้มาโดยผิดกฎหมาย ทำให้เงินที่ฟอกแล้วถูกนำกลับมาใช้ตามปกติ。',
          'กิจกรรมที่น่าสงสัย (Suspicious Activity): ธุรกรรมโดยผู้ใช้หรือบุคคลภายนอกที่บ่งชี้ว่าธุรกรรมนั้นอาจทำเพื่อวัตถุประสงค์ฉ้อโกงหรือผิดกฎหมาย。',
          'มาตรการคว่ำบาตร (Sanctions): มาตรการที่ชุมชนนานาชาติบังคับใช้เพื่อห้ามหรือจำกัดกิจกรรมที่ถูกคว่ำบาตร ตัวอย่างการใช้ ได้แก่：',
          '• กระตุ้นประเทศหรือรัฐบาลเป้าหมายให้เปลี่ยนพฤติกรรม；',
          '• กดดันประเทศเป้าหมายให้ปฏิบัติตามเป้าหมายที่กำหนด；',
          '• ใช้เป็นเครื่องมือบังคับเมื่อสันติภาพและความมั่นคงระหว่างประเทศถูกคุกคามและความพยายามทางการทูตล้มเหลว；',
          '• ป้องกันและปราบปรามการสนับสนุนทางการเงินแก่ผู้ก่อการร้ายหรือการกระทำของผู้ก่อการร้าย。',
        ],
      },
      {
        heading: '4. การกำกับดูแลและการตรวจสอบ (Governance & Oversight)',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} แต่งตั้ง Chief Compliance Officer (CCO) รับผิดชอบการประสานงานนโยบาย AML และการดำเนินโปรแกรม。`,
          'หน้าที่ของ CCO รวมถึงการพัฒนาโปรแกรม AML ปรับปรุงนโยบาย AML ร่วมกับผู้มีส่วนได้ส่วนเสีย ประเมินข้อกำหนดด้านกฎระเบียบใหม่ และตรวจสอบกิจกรรมที่น่าสงสัยหรือผิดปกติ。',
          `${VITE_OFFICIAL_NAME} ให้การฝึกอบรม AML เป็นประจำแก่พนักงานทุกคน。`,
        ],
      },
      {
        heading: '5. รู้จักลูกค้า (KYC) & การติดตามธุรกรรม (Transaction Monitoring)',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} ใช้มาตรการตรวจสอบผู้ใช้และการติดตามอย่างต่อเนื่องตามข้อกำหนดทางกฎหมาย เพื่อป้องกันการมีส่วนร่วมในกิจกรรมที่ผิดกฎหมายหรือไม่ได้รับอนุญาต โดยบังคับใช้ผ่านฟีเจอร์ซอฟต์แวร์และข้อตกลงการให้บริการ。`,
          'A. การตรวจสอบลูกค้า (Customer Due Diligence, CDD): ใช้วิธีการตามความเสี่ยงเพื่อทำความเข้าใจความสัมพันธ์ผู้ใช้–แพลตฟอร์มและสร้างโปรไฟล์ความเสี่ยง รวบรวมข้อมูลที่เกี่ยวข้องระหว่างการลงทะเบียน (เช่น ที่อยู่กระเป๋าเงิน อีเมล) และกำหนดมาตรการ CDD ที่แตกต่างตามประเภทบัญชี/บริการ。',
          '• การยืนยันตัวตนและอายุ: ผู้ให้บริการภายนอกยืนยันความถูกต้องของข้อมูลและเอกสาร KYC ตรวจสอบสิทธิ์ตามกฎหมาย และยืนยันว่าไม่ได้อยู่ในเขตอำนาจที่ถูกคว่ำบาตรหรือห้าม โดยตรวจสอบรายชื่อคว่ำบาตรทั่วโลกด้วยข้อมูล onboarding เช่น ที่อยู่กระเป๋าเงิน。',
          '• ข้อมูลลูกค้า: เก็บรายละเอียด เช่น ที่อยู่กระเป๋าเงิน ชื่อ ที่อยู่ ประเทศ วันเกิด หรือรหัสไปรษณีย์ (รวมเรียกว่า “ข้อมูล KYC”) ก่อนออกที่อยู่เติมเงิน (เช่น QR code) ปัจจุบันไม่อนุญาตผู้ใช้ที่ไม่ใช่บุคคลธรรมชาติ และอาจพึ่งพานิติบุคคลอื่นทำบาง/ทั้งหมดของ CIP。',
          '• การจำกัดภูมิศาสตร์สำหรับเขตอำนาจห้าม: ผู้ใช้ยืนยันว่าไม่ได้อยู่ในประเทศที่บริการถูกห้าม โดยตรวจสอบผ่าน geoblocking ตาม IP และต้องไม่อยู่ภายใต้มาตรการคว่ำบาตร/รายชื่อเฝ้าติดตามของสหรัฐฯ สหภาพยุโรป หรือระดับโลก (รวมถึงอิหร่าน คิวบา เกาหลีเหนือ ซีเรีย และไครเมีย)。',
          'สัญญาห้าม onboarding ผู้ใช้จากเขตอำนาจที่จำกัด และแจ้งว่าบริการไม่พร้อมให้ในพื้นที่ดังกล่าว นโยบายอ้างอิงมาตรฐานความเสี่ยง การป้องกันการฉ้อโกง AML และการประเมินความเหมาะสมในการให้บริการ。',
          'B. การตรวจสอบเข้มงวดเพิ่มเติม & การติดตามอย่างต่อเนื่อง (Enhanced Due Diligence & Ongoing Monitoring): ติดตามพฤติกรรมและตัวชี้วัดธงแดง เมื่อทริกเกอร์อาจระงับบัญชีและขอข้อมูลเพิ่มเติม เช่น ชื่อเต็ม สัญชาติ ที่อยู่ถาวร หมายเลขประจำตัว เอกสารยืนยันตัวตน แหล่งที่มาของเงินและทรัพย์สิน โดยอาจใช้ผู้ให้บริการภายนอกตรวจสอบ。',
          'C. นโยบายการยอมรับ (Acceptance Policy): ไม่ยอมรับ/บล็อกผู้ใช้ที่ไม่ให้ข้อมูลที่ร้องขอ ส่งเอกสารปลอม แอบอ้างตำแหน่ง มาจากเขตอำนาจจำกัด อยู่ภายใต้มาตรการคว่ำบาตร มีปัญหาการติดการพนันยาวนานหรือสุขภาพจิต ทำธุรกรรมจากเขตอำนาจจำกัดหรือใช้แหล่งเงินที่ถูกห้าม และสงวนสิทธิ์บล็อก/ระงับด้วยเหตุผลอื่น。',
          'การติดตามธุรกรรม (Transaction Monitoring): ปฏิบัติตามมาตรการคว่ำบาตรทางเศรษฐกิจและการค้า จัดทำโปรแกรมติดตามโดยผสานระบบกฎภายในและระบบบุคคลที่สาม เพื่อตรวจจับความผิดปกติแบบเรียลไทม์และต่อเนื่อง พร้อมนิยามกระบวนการระบุ–สอบสวน–ประเมิน–บันทึกกิจกรรมที่ผิดปกติหรืออาจสงสัย。',
          '• การติดตามเขตอำนาจและมาตรการคว่ำบาตร: ติดตามธุรกรรมจากพื้นที่ถูกคว่ำบาตร/ห้าม อาจเพิ่มการตรวจสอบเมื่อถอนเงิน ใช้การติดตามทั้งแมนนวลและอัตโนมัติ ปฏิเสธการถอนที่น่าสงสัยหรือขอข้อมูลเพิ่ม จำกัดการเติมเงินจากกระเป๋าที่เชื่อมโยงตลาดสหรัฐฯ ผู้ใช้อาจยื่นข้อมูลโต้แย้งการระงับตามมาตรฐาน KYC/การติดตามต่อเนื่อง。',
          '• การตรวจสอบมาตรการคว่ำบาตร: ตรวจสอบที่อยู่กระเป๋ากับฐานข้อมูลคว่ำบาตรก่อนออกที่อยู่เติมเงิน โดยใช้ผู้ให้บริการวิเคราะห์บล็อกเชนภายนอก เช่น Chainalysis และตรวจซ้ำตามรอบ。',
          '• การตรวจจับกิจกรรมที่น่าสงสัย: ตรวจสอบขนาด ความถี่ รูปแบบ หรือประเภทธุรกรรมโดยคำนึงถึงความเสี่ยงและธงแดง สร้างรายงานกิจกรรมผิดปกติ/เสี่ยงสูง/สงสัยเป็นประจำ。',
          '• มาตรการป้องกันการผสม (Anti-Mixing): ใช้ซอฟต์แวร์ตรวจจับรูปแบบฝาก/ถอนที่น่าสงสัย พิจารณาเป็นรายกรณีตามความเสี่ยง และอาจขอคำอธิบายการใช้แพลตฟอร์ม。',
          '• การตรวจสอบ Chainalysis: ทบทวนการฝาก–ถอนคริปโตทั้งหมด (ทางตรง/อ้อม) หากมีสัญญาณฉ้อโกงหรือสงสัย อาจระงับและตรวจสอบ บัญชีเสี่ยงสูงอาจต้องแสดงหลักฐานเงินทุน และอาจปฏิเสธการถอนไปยังที่อยู่เสี่ยงสูงตามคะแนนความเสี่ยง。',
          '• KYC สำหรับเกณฑ์การถอน: เมื่อถึงเกณฑ์การถอนตามโปรไฟล์ความเสี่ยง บัญชีจะถูกระงับจนกว่าจะทำ KYC เพียงพอแล้วเสร็จ。',
          'การควบคุมการติดตามต่อเนื่องเพิ่มเติม (Additional Ongoing Monitoring Controls): การตรวจจับหลายบัญชี (เชื่อมโยงบัญชีจากอุปกรณ์เดียวและห้ามโอน P2P ภายในแพลตฟอร์ม)；การติดตามโซนเวลา (ตรวจจับการซ่อนแหล่งที่มาผ่านเครื่องมือ geolocation)；การทบทวนผลิตภัณฑ์และบริการ (จำกัดสินทรัพย์ที่อัปโหลด รักษารายการสินทรัพย์ที่อนุญาต และห้ามใช้ mixers/tumblers/เหรียญหรือโทเคนบางประเภท)；การบริหารผู้ขาย (ประเมินผู้ให้บริการภายนอกเป็นประจำและขอข้อมูลเมื่อจำเป็น)；',
          'นวัตกรรมด้านความสอดคล้อง: ติดตามโซลูชันใหม่และทำโปรแกรมนำร่องเพื่อประเมินประสิทธิภาพ รวมถึงเครื่องมือเนทีฟบล็อกเชน เช่น บริการป้องกันการฉ้อโกงและผู้ให้บริการ KYC on-chain。',
          'การศึกษาและฝึกอบรม: ภายใต้คำแนะนำทางกฎหมายและการกำกับดูแลของ CCO จัดฝึกอบรม AML/CFT และการปฏิบัติตามมาตรการคว่ำบาตรแก่พนักงานตามความจำเป็น。',
          'การรายงาน: ต้องรายงานธุรกรรมที่ผิดปกติหรือสงสัยตามกฎหมาย ลูกค้าที่อยู่ในรายชื่อคว่ำบาตรหรือเกี่ยวข้องกับการฟอกเงิน การสนับสนุนการก่อการร้าย หรืออาชญากรรมอื่น จะถูกรายงานต่อหน่วยงานกำกับดูแลเป็นกิจกรรมที่น่าสงสัย。',
        ],
      },
    ],
  },
  'vi-VN': {
    title: 'TUYÊN BỐ CHỐNG RỬA TIỀN VÀ CHỐNG TÀI TRỢ KHỦNG BỐ',
    sections: [
      {
        heading: '1. Mô hình kinh doanh của công ty',
        paragraphs: [
          `Được thành lập vào năm 2017, ${VITE_OFFICIAL_NAME} hiện hỗ trợ người dùng tại hơn 169 quốc gia trên toàn thế giới.`,
          `Trong khuôn khổ hoạt động toàn cầu, ${VITE_OFFICIAL_NAME} đã thiết lập các biện pháp tuân thủ phù hợp với các dịch vụ và sản phẩm của mình, được thiết kế để ngăn chặn và phát hiện các hoạt động bất hợp pháp trên nền tảng.`,
          'Các biện pháp này bao gồm việc đăng ký và sàng lọc tuân thủ của khách hàng, cũng như các biện pháp kiểm soát dựa trên hành vi giao dịch.',
        ],
      },
      {
        heading: '2. Tuyên bố chính sách của công ty',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} không phải là một tổ chức tài chính theo luật pháp Curaçao và do đó không trực tiếp tuân theo các quy định áp dụng cho một số tổ chức tài chính, dịch vụ chuyển tiền hoặc nhà cung cấp dịch vụ tài sản ảo.`,
          `Theo hướng dẫn AML/CFT năm 2016 do Curaçao Gaming Control Board ban hành cho khu vực pháp lý Curaçao, ${VITE_OFFICIAL_NAME} nghiêm cấm và từ chối sử dụng sản phẩm của mình cho bất kỳ hoạt động bất hợp pháp nào, bao gồm rửa tiền, tài trợ khủng bố hoặc vi phạm lệnh trừng phạt thương mại, phù hợp với luật, quy định và chuẩn mực AML quốc gia.`,
          `${VITE_OFFICIAL_NAME} tiếp tục theo dõi các chuẩn mực do FATF, các nhóm ngành trò chơi liên quan và Curaçao Gaming Control Board đặt ra, và sẽ thực hiện các hành động cần thiết theo thay đổi pháp luật.`,
          `${VITE_OFFICIAL_NAME} mong muốn tuân thủ thông lệ tốt nhất toàn cầu nhằm ngăn sản phẩm bị sử dụng để tạo điều kiện cho các hoạt động nói trên.`,
          'Các thông lệ tốt nhất bao gồm:',
          '- Triển khai các chính sách, quy trình và kiểm soát bằng văn bản được thiết kế hợp lý để ngăn rửa tiền, tài trợ khủng bố và vi phạm trừng phạt thương mại;',
          '- Phân công cán bộ tuân thủ (khi cần) để giám sát việc thực thi chính sách, quy trình và kiểm soát;',
          '- Cung cấp chương trình đào tạo và giáo dục phù hợp cho nhân sự liên quan;',
          '- Độc lập xem xét, giám sát và duy trì các chính sách, quy trình và kiểm soát.',
        ],
      },
      {
        heading: '3. Định nghĩa',
        paragraphs: [
          'Rửa tiền: Quá trình làm cho tiền thu được bất hợp pháp có vẻ hợp pháp, thường gồm ba bước: ghi chép (Placement), phân tầng (Layering) và hợp nhất (Integration).',
          'Ghi chép (Placement): Gửi tiền bất hợp pháp vào tổ chức tài chính truyền thống qua tiền gửi hoặc phương tiện khác.',
          'Phân tầng (Layering): Tách tiền phạm tội khỏi nguồn gốc qua các giao dịch tài chính phức tạp (chuyển tiền mặt thành séc du lịch, lệnh chuyển tiền, chuyển khoản điện tử, thư tín dụng, cổ phiếu, trái phiếu, hoặc mua tài sản).',
          'Hợp nhất (Integration): Dùng các giao dịch có vẻ hợp pháp để che giấu tiền bất hợp pháp, phân phối lại cho tội phạm và tái hòa nhập vào sử dụng bình thường.',
          'Hoạt động đáng ngờ: Giao dịch của người dùng hoặc người không dùng dịch vụ cho thấy có thể phục vụ mục đích gian lận hoặc bất hợp pháp.',
          'Trừng phạt (Sanctions): Các biện pháp do cộng đồng quốc tế áp đặt để cấm/hạn chế hoạt động bị trừng phạt; ví dụ để khuyến khích quốc gia/chế độ mục tiêu thay đổi hành vi; gây sức ép tuân thủ mục tiêu; là công cụ thực thi khi hòa bình, an ninh quốc tế bị đe dọa và ngoại giao thất bại; ngăn và trấn áp tài trợ khủng bố hoặc hành vi khủng bố.',
        ],
      },
      {
        heading: '4. Quản trị và giám sát',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} bổ nhiệm Giám đốc Tuân thủ (Chief Compliance Officer, “CCO”) để điều phối thực thi chính sách và chương trình AML.`,
          'Trách nhiệm CCO gồm: xây dựng chương trình AML, cập nhật chính sách AML với các bên liên quan, đánh giá yêu cầu pháp lý mới, điều tra hoạt động nghi ngờ hoặc bất thường.',
          `${VITE_OFFICIAL_NAME} tổ chức đào tạo AML định kỳ cho toàn bộ nhân viên.`,
        ],
      },
      {
        heading: '5. Hiểu rõ khách hàng (KYC) và giám sát giao dịch',
        paragraphs: [
          `${VITE_OFFICIAL_NAME} áp dụng biện pháp thẩm định người dùng và giám sát liên tục theo yêu cầu pháp luật, nhằm ngăn người dùng tham gia hoạt động bất hợp pháp hoặc trái phép; việc tuân thủ được thực thi qua tính năng phần mềm và thỏa thuận dịch vụ.`,
          'A. Thẩm định Khách hàng (Customer Due Diligence, CDD): Cách tiếp cận dựa trên rủi ro để hiểu bản chất, mục đích quan hệ người dùng–nền tảng và xây dựng hồ sơ rủi ro cho từng khách hàng; thu thập thông tin phù hợp khi mở tài khoản; duy trì yêu cầu CDD khác nhau theo loại tài khoản/dịch vụ.',
          '— Chương trình Xác thực Khách hàng (CIP) gồm: thu thập thông tin cơ bản (địa chỉ ví, email) qua cổng onboarding; theo dõi hồ sơ rủi ro ví crypto nạp tiền; ghi lại thông tin định danh; kiểm tra người dùng có nằm trong danh sách khủng bố đã biết/nghi ngờ do tổ chức tài chính cung cấp hay không.',
          '— Biện pháp thực hiện: xác minh danh tính và độ tuổi bởi bên thứ ba; xác nhận quyền sử dụng hợp pháp; đảm bảo không ở khu vực bị trừng phạt/cấm; đối chiếu danh sách trừng phạt toàn cầu bằng dữ liệu onboarding (ví dụ địa chỉ ví).',
          '— Thông tin khách hàng: thu thập chi tiết (địa chỉ ví, họ tên, địa chỉ, quốc gia, ngày sinh, mã bưu điện – gọi chung là “Thông tin KYC”) trước khi cấp địa chỉ quỹ (ví dụ QR code); hiện chưa chấp nhận người dùng không phải cá nhân; có thể dựa vào tổ chức khác thực thi một phần/toàn bộ CIP.',
          '— Chặn địa lý với khu vực bị cấm: yêu cầu khách hàng theo hợp đồng xác nhận không ở quốc gia bị cấm, xác minh qua geoblocking dựa trên IP; không thuộc lệnh trừng phạt/danh sách theo dõi của Hoa Kỳ, EU hoặc toàn cầu (bao gồm Iran, Cuba, Bắc Triều Tiên, Syria và Crimea); xác minh bằng biện pháp dựa trên rủi ro như KYC và geoblocking.',
          `— Hợp đồng cấm nhận người dùng từ khu vực bị cấm; người dùng được thông báo ${VITE_OFFICIAL_NAME} không cung cấp dịch vụ tại khu vực hạn chế; chính sách dựa trên tiêu chuẩn rủi ro, chống gian lận, AML và đánh giá tính hợp pháp cung cấp dịch vụ.`,
          'B. Tăng cường thẩm định & giám sát liên tục (EDD & Ongoing Monitoring): Theo dõi liên tục để phát hiện hành vi/dấu hiệu liên quan đến rửa tiền/tài trợ khủng bố; khi kích hoạt chỉ số cảnh báo, tạm đình chỉ tài khoản và yêu cầu thông tin bổ sung, có thể gồm: họ tên đầy đủ, quốc tịch, địa chỉ thường trú, số giấy tờ tùy thân (mã số thuế/hộ chiếu/quốc gia cấp/ID nước ngoài…), giấy tờ tùy thân, nguồn tiền và tài sản; có thể dùng bên thứ ba xác minh.',
          `C. Chính sách chấp nhận: Không chấp nhận và sẽ chặn người dùng không cung cấp thông tin yêu cầu; cung cấp giấy tờ giả; gian lận vị trí; đến từ khu vực bị hạn chế/cấm; thuộc lệnh trừng phạt/danh sách theo dõi; nghiện cờ bạc dài hạn hoặc vấn đề sức khỏe tâm thần; giao dịch từ khu vực hạn chế hoặc dùng nguồn tiền bị cấm. ${VITE_OFFICIAL_NAME} bảo lưu quyền chặn/đình chỉ vì lý do khác.`,
          'Giám sát giao dịch: Tuân thủ nghiêm các chương trình trừng phạt kinh tế, thương mại tại khu vực hoạt động; thiết lập chương trình giám sát giao dịch kết hợp hệ thống quy tắc nội bộ và hệ thống bên thứ ba để nhận diện bất thường theo thời gian thực và liên tục; mô tả phương pháp nhận diện qua xác minh nhân viên/khách hàng, yêu cầu cơ quan thực thi pháp luật, báo cáo hệ thống,… tập trung điều tra, đánh giá, ghi nhận cảnh báo.',
          '— Giám sát khu vực bị trừng phạt/bị cấm: theo dõi giao dịch từ các khu vực này; có thể áp dụng yêu cầu thẩm định khi rút tiền; kết hợp thủ công–tự động để nhận diện “cờ đỏ”; có thể từ chối rút tiền đáng ngờ hoặc yêu cầu thông tin bổ sung; hạn chế người dùng cố gắng huy động vốn từ khu vực bị cấm (công bố trong UI và cập nhật nội bộ); ví liên quan sàn Hoa Kỳ có thể bị chặn; người dùng có thể kháng nghị bằng thông tin bổ sung theo tiêu chuẩn KYC/giám sát liên tục.',
          '— Sàng lọc trừng phạt: trước khi cấp địa chỉ quỹ, sàng lọc địa chỉ ví với cơ sở dữ liệu trừng phạt bằng nhà cung cấp pháp y blockchain bên thứ ba như Chainalysis; tái sàng lọc định kỳ.',
          '— Nhận dạng hoạt động bất thường: giám sát quy mô, tần suất, mô hình, loại giao dịch với yếu tố rủi ro/chỉ báo cảnh báo; lập báo cáo thường xuyên về hoạt động bất thường, rủi ro cao hoặc đáng ngờ.',
          '— Biện pháp chống “mixing”: dùng phần mềm phát hiện mẫu gửi/rút đáng ngờ; xử lý theo từng trường hợp dựa trên rủi ro; có thể yêu cầu người dùng giải thích mục đích/phương thức sử dụng nền tảng.',
          '— Kiểm toán Chainalysis: mọi nạp/rút crypto (trực tiếp/gián tiếp) đều được rà soát; tài khoản bị cảnh báo có thể bị tạm ngưng và kiểm toán; tài khoản rủi ro cao có thể phải chứng minh nguồn tiền; có thể từ chối rút đến địa chỉ “rủi ro cao”.',
          '— KYC ngưỡng rút tiền: bất kể vị trí/liên kết, khi tài khoản đạt ngưỡng rút theo hồ sơ rủi ro sẽ bị tạm ngưng cho tới khi hoàn tất KYC đầy đủ.',
          `Các kiểm soát giám sát liên tục bổ sung: dùng phần mềm bên thứ ba phát hiện nhiều tài khoản (liên kết tài khoản truy cập từ cùng thiết bị); giám sát hoạt động trong nền tảng và cấm chuyển khoản P2P nội bộ; mọi rút tiền phải tuân quy trình xác minh của ${VITE_OFFICIAL_NAME} và bên thứ ba;`,
          'Giám sát múi giờ: đối chiếu thông tin thiết bị với khu vực bị hạn chế để phát hiện ý đồ che giấu nguồn kết nối bằng công cụ định vị địa lý.',
          'Đánh giá sản phẩm & dịch vụ: quy trình bổ sung ngăn khai thác nền tảng; người dùng phải tuân thủ điều khoản sử dụng; biện pháp bảo vệ giảm rủi ro lạm dụng (giới hạn loại tài sản được tải lên; duy trì danh mục tài sản cho phép; cấm mixers/blenders/một số coin/token ẩn danh—phát hiện sẽ cấm ngay).',
          'Quản lý nhà cung cấp: hợp tác nhà cung cấp uy tín; đánh giá định kỳ năng lực và tính tuân thủ hợp đồng; áp dụng biện pháp khắc phục khi cần; có thể yêu cầu cung cấp thông tin trong quy trình thẩm định nhà cung cấp.',
          'Đổi mới tuân thủ: theo dõi cơ chế tuân thủ mới, thử nghiệm/thí điểm quy mô nhỏ để đánh giá hiệu quả; công cụ gốc blockchain gồm dịch vụ chống gian lận, nhà cung cấp KYC on-chain và công cụ liên quan.',
          'Giáo dục & Đào tạo: với hỗ trợ cố vấn pháp lý và giám sát của CCO, cung cấp đào tạo định kỳ về AML, chống tài trợ khủng bố và tuân thủ trừng phạt khi cần.',
          `Báo cáo: theo luật quốc gia, ${VITE_OFFICIAL_NAME} có nghĩa vụ báo cáo mọi giao dịch bất thường hoặc đáng ngờ; khách hàng nằm trong danh sách trừng phạt hoặc liên quan rửa tiền, tài trợ khủng bố hay tội phạm khác sẽ được báo cáo là hoạt động đáng ngờ cho cơ quan quản lý.`,
        ],
      },
    ],
  },

}
