<script lang="ts" setup>
import { getLang } from '@tg/vue-i18n'

const lang = getLang()

const t = {
  'en-US': {
    title: 'Random Number Generation',
    desc1: 'For each verifiable bet, a client seed, a server seed, a nonce and a cursor are used as the input parameters for the random number generation function. This function utilises the cryptographic hash function HMAC_SHA256 to generate bytes which are then used as the foundation for how we generate provably fair random outcomes on our platform.',
    serverSeed: 'Server Seed',
    serverSeed1: 'The server seed is generated by our system as a random 64-character hex string. You are then provided with an encrypted hash of that generated server seed before you place any bets. The reason we provide you with the encrypted form of the server seed is to ensure that the un-hashed server seed cannot be changed by the casino operator, and that the player cannot calculate the results beforehand.',
    serverSeed2: 'To reveal the server seed from its hashed version, the seed must be rotated by the player, which triggers the replacement with a newly generated one.',
    serverSeed3: 'From this point you are able to verify that the hashed server seed matches that of the un-hashed server seed. This process can be verified via our un-hashed server seed function found in the menu above.',
    clientSeed: 'Client Seed',
    clientSeed1: 'The client seed belongs to the player and is used to ensure they have influence on the randomness of the outcomes generated. Without this component of the algorithm, the server seed alone would have complete leverage over the outcome of each bet.',
    clientSeed2: 'All players are free to edit and change their client seed regularly to create a new chain of random upcoming outcomes. This ensures the player has absolute control over the generation of the result, similar to cutting the deck at a brick and mortar casino.',
    clientSeed3: 'During registration, a client seed is created for you by your browser, to ensure your initial experience with the site goes uninterrupted. Whilst this randomly generated client seed is considered suitable, we highly recommend that you choose your own, so that your influence is included in the randomness.',
    clientSeed4: 'You can do this via the fairness modal.',
    nonce: 'Nonce',
    nonce1: 'The nonce is simply a number that increments as every new bet is made. Due to the nature of the SHA256 cryptographic function, this creates a completely new result each time, without having to generate a new client seed and server seed.',
    nonce2: 'The implementation of nonce ensures we remain committed to your client seed and server seed pair, whilst generating new results for each bet placed.',
    cursor: 'Cursor (Incremental Number)',
    cursor1: 'We use 4 bytes of data to generate a single game result, and because SHA256 is limited to 32 bytes, we utilise this implementation of a cursor to give us the ability to create more game events without having to modify our provable fair algorithm.',
    cursor2: 'The cursor is only iterated over when the game being played requires the generation of more than 8 (32 bytes / 4 bytes) possible outcomes. For example: when we need to use more than 8 cards in a game of blackjack.',
    cursor3: 'The cursor starts as 0 and gets increased by 1 every time the 32 bytes are returned by the HMAC_SHA256 function. If we don’t require more than 8 random numbers to be generated for the game events, then the cursor does not increment as there is no need to generate any additional possible game outcomes.',
    moreThanOne: 'Games with More Than 1 Incremental Number:',
    plinko: 'Plinko (2 increments per game to cover possible 16 decisions)',
    defaultZeroTitle: 'Games with More Than 1 Incremental Number (Represented as Default Value 0):',
    dice: 'Dice',
    limbo: 'Limbo',
  },
  'zh-CN': {
    title: '随机数生成',
    desc1: '对于每一次可验证的投注，将使用客户端种子（Client Seed）、服务器种子（Server Seed）、随机数增量（Nonce）和游标（Cursor）作为随机数生成函数的输入参数。此函数利用加密哈希函数 HMAC_SHA256 来生成字节，这些字节将作为我们平台生成可验证公平随机结果的基础。',
    serverSeed: '服务器种子',
    serverSeed1: '服务器种子由系统生成，为一个随机的 64 位十六进制字符串。在您下注之前，我们会提供该服务器种子的加密哈希值。提供加密形式的服务器种子，是为了保证赌场运营方无法更改未哈希的服务器种子，同时玩家也无法提前计算结果。',
    serverSeed2: '要从哈希版本中揭示服务器种子，玩家必须进行旋转（rotate），触发其被替换为新生成的种子。',
    serverSeed3: '从此，您可以验证哈希服务器种子是否与未哈希服务器种子一致。此过程可通过上方菜单中的“未哈希服务器种子”功能进行验证。',
    clientSeed: '客户端种子',
    clientSeed1: '客户端种子属于玩家，用于确保玩家对生成结果的随机性有影响。如果没有此算法组件，仅凭服务器种子，系统将完全控制每次投注的结果。',
    clientSeed2: '所有玩家均可自由编辑和更改客户端种子，以生成新的随机结果链。这保证玩家对结果生成拥有完全控制权，类似于实体赌场中的洗牌操作。',
    clientSeed3: '在注册时，浏览器会为您生成一个客户端种子，以确保您初次体验网站时不中断。虽然此随机生成的客户端种子已可使用，但我们强烈建议您自行设置种子，以便您的影响力被包含在随机性中。',
    clientSeed4: '您可以通过“公平性”弹窗来设置客户端种子。',
    nonce: '随机数增量（Nonce）',
    nonce1: 'Nonce 是一个随着每次新投注而递增的数字。由于 SHA256 加密函数的特性，每次生成的结果都是全新的，无需生成新的客户端种子和服务器种子。',
    nonce2: 'Nonce 的实现确保了我们对您客户端种子和服务器种子的承诺，同时为每次投注生成新的结果。',
    cursor: '游标（递增数）',
    cursor1: '我们使用 4 个字节生成单个游戏结果，而 SHA256 限制为 32 字节，因此我们使用游标的实现来生成更多游戏事件，而无需修改可验证公平算法。',
    cursor2: '只有当游戏需要生成超过 8 个可能结果（32 字节 / 4 字节）时，游标才会迭代。例如：在二十一点（Blackjack）中需要使用超过 8 张牌时。',
    cursor3: '游标初始值为 0，每次 HMAC_SHA256 返回 32 个字节后增加 1。如果游戏事件不需要生成超过 8 个随机数，则游标不递增，因为无需生成额外的可能结果。',
    moreThanOne: '使用多个增量数的游戏:',
    plinko: 'Plinko （每局 2 次增量以覆盖 16 种可能决策）',
    defaultZeroTitle: '使用多个增量数的游戏（默认值 0 表示）:',
    dice: 'Dice',
    limbo: 'Limbo',
  },
  'ja-JP': {
    title: '乱数生成',
    desc1: '検証可能な賭けごとに、クライアントシード、サーバーシード、ナンス、カーソルが入力パラメータとして使用されます。この関数は暗号ハッシュ関数 HMAC_SHA256 を利用してバイトを生成し、これが当プラットフォーム上で公平性が証明されるランダムな結果を生成するための基礎となります。',
    serverSeed: 'サーバーシード',
    serverSeed1: 'サーバーシードは、当社のシステムによってランダムな64文字の16進文字列として生成されます。その後、ベットを行う前に、生成されたサーバーシードの暗号化されたハッシュが提供されます。暗号化されたサーバーシードを提供する理由は、ハッシュ化されていないサーバーシードがカジノ運営者によって変更されることを防ぎ、プレイヤーが事前に結果を計算できないようにするためです。',
    serverSeed2: 'ハッシュ化されたバージョンからサーバーシードを明らかにするには、シードをプレイヤーがローテーションして、新しく生成されたシードに置き換える必要があります。',
    serverSeed3: 'この時点で、ハッシュ化されたサーバーシードがハッシュ化されていないサーバーシードと一致していることを確認できます。このプロセスは、上部のメニューにあるハッシュ化されていないサーバーシード機能を使用して確認できます。',
    clientSeed: 'クライアントシード',
    clientSeed1: 'クライアントシードはプレイヤーに属し、生成される結果のランダム性に影響を与えるために使用されます。アルゴリズムのこの要素がなければ、サーバーシードのみが各ベットの結果に完全に影響を及ぼしてしまいます。',
    clientSeed2: 'すべてのプレイヤーは、クライアントシードを定期的に編集・変更することで、ランダムな結果の連鎖を新たに作成できます。これにより、プレイヤーは結果の生成を完全にコントロールでき、まるで実店舗のカジノでデッキをカットするのと同じような感覚でゲームを進めることができます。',
    clientSeed3: '登録時に、ブラウザによってクライアントシードが生成されます。これは、サイトの初期エクスペリエンスが中断されないようするためです。このランダムに生成されたクライアントシードは適切であると考えられていますが、ランダム性にあなたの影響が反映されるよう、ご自身でクライアントシードを選択することを強くお勧めします。',
    clientSeed4: 'これは公平性モーダルを介して実行できます。',
    nonce: 'ナンス',
    nonce1: 'nonceは、新しい賭けが行われるたびに増加する単純な数値です。SHA256暗号化関数の性質上、クライアントシードとサーバーシードを新たに生成することなく、毎回完全に新しい結果が生成されます。',
    nonce2: 'nonce の実装により、賭けが行われるたびに新しい結果が生成されながら、クライアントシードとサーバーシードのペアが維持されることが保証されます。',
    cursor: 'カーソル（増分番号）',
    cursor1: '1 つのゲーム結果を生成するために 4 バイトのデータを使用します。SHA256 は 32 バイトに制限されているため、このカーソルの実装を利用することで、公平性が証明されるアルゴリズムを変更することなく、より多くのゲームイベントを作成できるようになります。',
    cursor2: 'カーソルは、プレイ中のゲームで8つを超える結果の生成が必要な場合にのみ反復処理されます。例えば、ブラックジャックで8枚以上のカードを使用する必要がある場合などです。',
    cursor3: 'カーソルは0から始まり、HMAC_SHA256関数によって32バイトが返されるたびに1ずつ増加します。ゲームイベントに8個以上の乱数を生成する必要がない場合、追加のゲーム結果を生成する必要がないため、カーソルは増加しません。',
    moreThanOne: '1つ以上の増分番号を持つゲーム:',
    plinko: 'Plinko（ゲームごとに2つの増分があり、16の決定をカバーします）',
    defaultZeroTitle: '増分数が 1 を超えるゲーム (デフォルト値 0 として表されます):',
    dice: 'サイコロ',
    limbo: 'リンボ',
  },
  'ko-KR': {
    title: '난수 생성',
    desc1: '검증 가능한 각 베팅에 대해 클라이언트 시드, 서버 시드, nonce 및 커서가 난수 생성 함수의 입력 매개변수로 사용됩니다. 이 함수는 암호화 해시 함수 HMAC_SHA256를 활용하여 바이트를 생성하고, 이를 기반으로 플랫폼에서 공정성이 입증된 무작위 결과를 생성합니다.',
    serverSeed: '서버 시드',
    serverSeed1: '서버 시드는 저희 시스템에서 무작위 64자리 16진수 문자열로 생성됩니다. 베팅하기 전에 생성된 서버 시드의 암호화된 해1값이 제공됩니다. 저희가 암호화된 형태의 서버 시드를 제공하는 이유는 카지노 운영자가 해시되지 않은 서버 시드를 변경할 수 없도록 하고, 플레이어가 결과를 미리 계산할 수 없도록 하기 위함입니다.',
    serverSeed2: '해시된 버전에서 서버 시드를 공개하려면 플레이어가 시드를 회전해야 하며, 그러면 새로 생성된 시드로 교체됩니다.',
    serverSeed3: '이 시점에서 해시된 서버 시드가 해시되지 않은 서버 시드와 일치하는지 확인할 수 있습니다. 이 과정은 위 메뉴에 있는 해시되지 않은 서버 시드 기능을 통해 확인할 수 있습니다.',
    clientSeed: '클라이언트 시드',
    clientSeed1: '클라이언트 시드는 플레이어에게 속하며, 생성된 결과의 무작위성에 영향을 미치는 데 사용됩니다. 알고리즘의 이 구성 요소가 없다면, 서버 시드만으로도 각 베팅의 결과에 완전한 영향력을 행사할 수 있습니다.',
    clientSeed2: '모든 플레이어는 클라이언트 시드를 정기적으로 편집하고 변경하여 무작위로 생성되는 새로운 결과 체인을 만들 수 있습니다. 이를 통해 플레이어는 오프라인 카지노에서 카드를 자르는 것처럼 결과 생성에 대한 완전한 통제권을 확보할 수 있습니다.',
    clientSeed3: '등록 시, 사이트 이용 초기 경험이 중단 없이 지속될 수 있도록 브라우저에서 클라이언트 시드를 생성합니다. 무작위로 생성된 클라이언트 시드는 적절한 것으로 간주되지만, 무작위성에 영향을 미칠 수 있으므로 직접 클라이언트 시드를 선택하는 것이 좋습니다.',
    clientSeed4: '공정성 모달을 통해 이를 수행할 수 있습니다.',
    nonce: '논스',
    nonce1: '논스는 새로운 베팅이 이루어질 때마다 증가하는 숫자입니다. SHA256 암호화 함수의 특성상, 새로운 클라이언트 시드와 서버 시드를 생성하지 않고도 매번 완전히 새로운 결과가 생성됩니다.',
    nonce2: 'nonce를 구현하면 각 베팅에 대해 새로운 결과를 생성하는 동시에 클라이언트 시드와 서버 시드 쌍을 준수할 수 있습니다.',
    cursor: '커서(증분 번호)',
    cursor1: '우리는 하나의 게임 결과를 생성하는 데 4바이트의 데이터를 사용하며, SHA256은 32바이트로 제한되어 있기 때문에, 우리는 증명 가능한 공정 알고리즘을 수정하지 않고도 더 많은 게임 이벤트를 생성할 수 있는 커서 구현을 활용합니다.',
    cursor2: '커서는 게임에서 8개 이상의 가능한 결과를 생성해야 할 때만 반복됩니다. 예를 들어, 블랙잭 게임에서 8장 이상의 카드를 사용해야 하는 경우입니다.',
    cursor3: '커서는 0으로 시작하여 HMAC_SHA256 함수가 32바이트를 반환할 때마다 1씩 증가합니다. 게임 이벤트에 대해 8개 이상의 난수 생성이 필요하지 않으면, 추가적인 게임 결과를 생성할 필요가 없으므로 커서가 증가하지 않습니다.',
    moreThanOne: '1개 이상의 증분 숫자가 있는 게임:',
    plinko: 'Plinko(게임당 2개의 증가로 16가지 결정 가능)',
    defaultZeroTitle: '1개 이상의 증분 숫자가 있는 게임(기본값 0으로 표시):',
    dice: '주사위',
    limbo: '림보',
  },
  'th-TH': {
    title: 'การสร้างตัวเลขสุ่ม',
    desc1: 'สำหรับการเดิมพันที่ตรวจสอบได้แต่ละครั้ง เมล็ดพันธุ์ไคลเอนต์ เมล็ดพันธุ์เซิร์ฟเวอร์ nonce และเคอร์เซอร์จะถูกใช้เป็นพารามิเตอร์อินพุตสำหรับฟังก์ชันการสร้างตัวเลขสุ่ม ฟังก์ชันนี้ใช้ HMAC_SHA256 เพื่อสร้างไบต์ซึ่งจะใช้เป็นพื้นฐานสำหรับวิธีการสร้างผลลัพธ์สุ่มที่ยุติธรรมและพิสูจน์ได้บนแพลตฟอร์มของเรา',
    serverSeed: 'เมล็ดพันธุ์เซิร์ฟเวอร์',
    serverSeed1: 'ระบบของเราสร้าง seed ของเซิร์ฟเวอร์ในรูปแบบสตริงเลขฐานสิบหกแบบสุ่ม 64 ตัวอักษร จากนั้นคุณจะได้รับแฮชที่เข้ารหัสของ seed ของเซิร์ฟเวอร์ที่สร้างขึ้นก่อนวางเดิมพันใดๆ เหตุผลที่เราให้ seed ของเซิร์ฟเวอร์แบบเข้ารหัสแก่คุณคือเพื่อให้แน่ใจว่าผู้ให้บริการคาสิโนจะไม่สามารถเปลี่ยนแปลง seed ของเซิร์ฟเวอร์ที่ไม่ได้แฮชได้ และผู้เล่นจะไม่สามารถคำนวณผลลัพธ์ล่วงหน้าได้',
    serverSeed2: 'หากต้องการเปิดเผยเมล็ดพันธุ์เซิร์ฟเวอร์จากเวอร์ชันแฮช ผู้เล่นจะต้องหมุนเมล็ดพันธุ์ ซึ่งจะทำให้มีการแทนที่ด้วยเมล็ดพันธุ์ที่สร้างขึ้นใหม่',
    serverSeed3: 'จากจุดนี้ คุณจะสามารถตรวจสอบได้ว่าค่า seed ของเซิร์ฟเวอร์ที่ถูกแฮชนั้นตรงกับค่า seed ของเซิร์ฟเวอร์ที่ไม่ได้ถูกแฮชหรือไม่ สามารถตรวจสอบกระบวนการนี้ได้ผ่านฟังก์ชัน seed ของเซิร์ฟเวอร์ที่ไม่ได้ถูกแฮช ซึ่งอยู่ในเมนูด้านบน',
    clientSeed: 'เมล็ดพันธุ์ลูกค้า',
    clientSeed1: 'เมล็ดพันธุ์ของไคลเอนต์เป็นของผู้เล่น และถูกใช้เพื่อให้แน่ใจว่าผู้เล่นมีอิทธิพลต่อความสุ่มของผลลัพธ์ที่เกิดขึ้น หากไม่มีส่วนประกอบนี้ของอัลกอริทึม เมล็ดพันธุ์ของเซิร์ฟเวอร์เพียงอย่างเดียวจะมีอำนาจเหนือผลลัพธ์ของการเดิมพันแต่ละครั้งได้อย่างสมบูรณ์',
    clientSeed2: 'ผู้เล่นทุกคนสามารถแก้ไขและเปลี่ยนลำดับของผู้เล่นได้อย่างสม่ำเสมอเพื่อสร้างชุดผลลัพธ์แบบสุ่มที่จะเกิดขึ้น วิธีนี้ช่วยให้ผู้เล่นสามารถควบคุมการสร้างผลลัพธ์ได้อย่างสมบูรณ์ คล้ายกับการตัดไพ่ในคาสิโนแบบดั้งเดิม',
    clientSeed3: 'ระหว่างการลงทะเบียน เบราว์เซอร์ของคุณจะสร้าง seed ไคลเอนต์ให้คุณ เพื่อให้มั่นใจว่าประสบการณ์เริ่มต้นของคุณกับเว็บไซต์จะราบรื่น แม้ว่า seed ไคลเอนต์ที่สร้างขึ้นแบบสุ่มนี้จะถือว่าเหมาะสม แต่เราขอแนะนำอย่างยิ่งให้คุณเลือก seed ของคุณเอง เพื่อให้อิทธิพลของคุณรวมอยู่ในความสุ่มนี้',
    clientSeed4: 'คุณสามารถทำได้ผ่านโหมดความยุติธรรม',
    nonce: 'โนนซ์',
    nonce1: 'ตัวเลข nonce เป็นเพียงตัวเลขที่เพิ่มขึ้นเรื่อยๆ ทุกครั้งที่มีการเดิมพันใหม่ เนื่องจากลักษณะของฟังก์ชันการเข้ารหัส SHA256 ฟังก์ชันนี้จึงสร้างผลลัพธ์ใหม่ทุกครั้ง โดยไม่ต้องสร้าง seed ของไคลเอนต์และ seed ของเซิร์ฟเวอร์ใหม่',
    nonce2: 'การนำ nonce มาใช้ รับประกันว่าเราจะมุ่งมั่นกับคู่เมล็ดพันธุ์ของลูกค้าและคู่เมล็ดพันธุ์ของเซิร์ฟเวอร์ของคุณ ในขณะที่สร้างผลลัพธ์ใหม่สำหรับการเดิมพันแต่ละครั้งที่วางไว้',
    cursor: 'เคอร์เซอร์ (ตัวเลขเพิ่ม)',
    cursor1: 'เราใช้ข้อมูล 4 ไบต์เพื่อสร้างผลลัพธ์เกมเดียว และเนื่องจาก SHA256 จำกัดขนาดไว้ที่ 32 ไบต์ เราจึงใช้การใช้งานเคอร์เซอร์นี้เพื่อให้เราสามารถสร้างกิจกรรมเกมเพิ่มเติมได้โดยไม่ต้องปรับเปลี่ยนอัลกอริทึมที่พิสูจน์ได้ว่ายุติธรรมของเรา',
    cursor2: 'เคอร์เซอร์จะถูกวนซ้ำเฉพาะเมื่อเกมที่กำลังเล่นต้องการผลลัพธ์ที่เป็นไปได้มากกว่า 8 รายการ (32 ไบต์ / 4 ไบต์) ตัวอย่างเช่น เมื่อเราต้องใช้ไพ่มากกว่า 8 ใบในเกมแบล็คแจ็ค',
    cursor3: 'เคอร์เซอร์เริ่มต้นที่ 0 และเพิ่มขึ้นทีละ 1 ทุกครั้งที่ฟังก์ชัน HMAC_SHA256 ส่งคืนค่า 32 ไบต์ หากเราไม่ต้องการตัวเลขสุ่มมากกว่า 8 ตัวสำหรับเหตุการณ์ในเกม เคอร์เซอร์จะไม่เพิ่มขึ้น เนื่องจากไม่จำเป็นต้องสร้างผลลัพธ์ที่เป็นไปได้เพิ่มเติมในเกม',
    moreThanOne: 'เกมที่มีจำนวนเพิ่มขึ้นมากกว่า 1:',
    plinko: 'Plinko (เพิ่ม 2 ครั้งต่อเกมเพื่อให้ครอบคลุมการตัดสินใจที่เป็นไปได้ 16 ครั้ง)',
    defaultZeroTitle: 'เกมที่มีตัวเลขเพิ่มขึ้นมากกว่า 1 ตัว (แสดงเป็นค่าเริ่มต้น 0):',
    dice: 'ลูกเต๋า',
    limbo: 'ลิมโบ้',
  },
  'vi-VN': {
    title: 'Tạo số ngẫu nhiên',
    desc1: 'Đối với mỗi lần đặt cược có thể xác minh, hạt giống máy khách, hạt giống máy chủ, nonce và con trỏ được sử dụng làm tham số đầu vào cho hàm tạo số ngẫu nhiên. Hàm này sử dụng hàm băm mật mã HMAC_SHA256 để tạo ra các byte, làm cơ sở cho nền tảng của chúng tôi tạo ra các kết quả ngẫu nhiên có thể xác minh và công bằng.',
    serverSeed: 'Hạt giống máy chủ',
    serverSeed1: 'Hạt giống máy chủ được hệ thống tạo ra dưới dạng một chuỗi thập lục phân 64 bit ngẫu nhiên. Trước khi bạn đặt cược, chúng tôi cung cấp hàm băm mật mã của hạt giống máy chủ này. Việc cung cấp hạt giống máy chủ mật mã đảm bảo rằng nhà điều hành sòng bạc không thể thay đổi hạt giống máy chủ không thể băm và người chơi không thể tính toán trước kết quả.',
    serverSeed2: 'Để hiển thị hạt giống máy chủ từ phiên bản băm, người chơi phải xoay vòng, kích hoạt việc thay thế nó bằng hạt giống mới được tạo.',
    serverSeed3: 'Từ thời điểm này, bạn có thể xác minh rằng hạt giống máy chủ đã băm khớp với hạt giống máy chủ không thể băm. Quá trình này có thể được xác minh bằng chức năng "Hạt giống máy chủ không thể băm" trong menu ở trên.',
    clientSeed: 'Hạt giống Khách hàng',
    clientSeed1: 'Hạt giống khách hàng thuộc về người chơi và được sử dụng để đảm bảo người chơi có ảnh hưởng đến tính ngẫu nhiên của kết quả được tạo ra. Nếu không có thành phần thuật toán này, hệ thống sẽ có toàn quyền kiểm soát kết quả của mỗi lần đặt cược chỉ dựa trên hạt giống máy chủ.',
    clientSeed2: 'Tất cả người chơi có thể tự do chỉnh sửa và thay đổi hạt giống khách hàng để tạo ra các chuỗi kết quả ngẫu nhiên mới. Điều này đảm bảo người chơi có toàn quyền kiểm soát việc tạo kết quả, tương tự như việc xáo bài trong sòng bạc truyền thống.',
    clientSeed3: 'Sau khi đăng ký, trình duyệt của bạn sẽ tạo một hạt giống khách hàng để đảm bảo trải nghiệm không bị gián đoạn khi bạn truy cập trang web lần đầu tiên. Mặc dù hạt giống khách hàng được tạo ngẫu nhiên này có sẵn, chúng tôi đặc biệt khuyên bạn nên tự thiết lập hạt giống của mình để ảnh hưởng của bạn được bao gồm trong tính ngẫu nhiên.',
    clientSeed4: 'Bạn có thể thiết lập hạt giống khách hàng của mình thông qua cửa sổ bật lên "Công bằng".',
    nonce: 'Tăng số ngẫu nhiên (Nonce)',
    nonce1: 'Nonce là một số tăng dần với mỗi lần đặt cược mới. Do đặc tính của hàm mã hóa SHA256, mỗi kết quả được tạo ra đều hoàn toàn mới, loại bỏ nhu cầu tạo hạt giống máy khách và máy chủ mới.',
    nonce2: 'Việc triển khai Nonce đảm bảo cam kết của chúng tôi đối với hạt giống máy khách và máy chủ của bạn trong khi tạo ra kết quả mới cho mỗi lần đặt cược.',
    cursor: 'Con trỏ (Số tăng dần)',
    cursor1: 'Chúng tôi sử dụng 4 byte để tạo ra một kết quả trò chơi duy nhất, trong khi SHA256 bị giới hạn ở 32 byte. Do đó, chúng tôi sử dụng triển khai con trỏ để tạo ra nhiều sự kiện trò chơi hơn mà không cần sửa đổi thuật toán công bằng có thể kiểm chứng.',
    cursor2: 'Con trỏ chỉ lặp lại khi trò chơi yêu cầu tạo ra nhiều hơn 8 kết quả khả thi (32 byte / 4 byte). Ví dụ: trong trò chơi Blackjack, khi cần nhiều hơn 8 lá bài.',
    cursor3: 'Con trỏ được khởi tạo thành 0 và tăng thêm 1 mỗi khi HMAC_SHA256 trả về 32 byte. Nếu một sự kiện trò chơi không yêu cầu tạo ra nhiều hơn 8 số ngẫu nhiên, con trỏ sẽ không tăng dần vì không cần thêm kết quả khả thi nào nữa.',
    moreThanOne: 'Trò chơi sử dụng nhiều mức tăng dần:',
    plinko: 'Plinko (2 mức tăng dần mỗi vòng để bao gồm 16 quyết định có thể xảy ra)',
    defaultZeroTitle: 'Trò chơi sử dụng nhiều mức tăng dần (mặc định là 0):',
    dice: 'Xúc xắc',
    limbo: 'Limbo',
  },
  'hi-IN': {
    title: 'यादृच्छिक संख्या निर्माण',
    desc1: 'प्रत्येक सत्यापन योग्य दांव के लिए, एक क्लाइंट सीड, एक सर्वर सीड, एक नॉन्स और एक कर्सर को यादृच्छिक संख्या निर्माण फ़ंक्शन के इनपुट पैरामीटर के रूप में उपयोग किया जाता है। यह फ़ंक्शन बाइट्स उत्पन्न करने के लिए क्रिप्टोग्राफ़िक हैश फ़ंक्शन HMAC_SHA256 का उपयोग करता है, जिनका उपयोग हमारे प्लेटफ़ॉर्म पर प्रमाणित रूप से निष्पक्ष यादृच्छिक परिणाम उत्पन्न करने के तरीके के आधार के रूप में किया जाता है।',
    serverSeed: 'सर्वर सीड',
    serverSeed1: 'सर्वर सीड हमारी प्रणाली द्वारा एक यादृच्छिक 64-वर्ण हेक्स स्ट्रिंग के रूप में जनरेट किया जाता है। फिर, कोई भी दांव लगाने से पहले, आपको उस जनरेट किए गए सर्वर सीड का एक एन्क्रिप्टेड हैश प्रदान किया जाता है। हम आपको सर्वर सीड का एन्क्रिप्टेड रूप इसलिए प्रदान करते हैं ताकि यह सुनिश्चित हो सके कि कैसीनो संचालक अन-हैश्ड सर्वर सीड को बदल न सके और खिलाड़ी पहले से परिणामों की गणना न कर सके।',
    serverSeed2: 'सर्वर सीड को उसके हैश्ड संस्करण से प्रकट करने के लिए, खिलाड़ी को सीड को घुमाना होगा, जिससे उसका प्रतिस्थापन एक नए जनरेट किए गए सीड से हो जाएगा।',
    serverSeed3: 'इस बिंदु से, आप यह सत्यापित कर सकते हैं कि हैश्ड सर्वर सीड अन-हैश्ड सर्वर सीड से मेल खाता है। इस प्रक्रिया को ऊपर दिए गए मेनू में अन-हैश्ड सर्वर सीड फ़ंक्शन के माध्यम से सत्यापित किया जा सकता है।',
    clientSeed: 'क्लाइंट सीड',
    clientSeed1: 'क्लाइंट सीड खिलाड़ी का होता है और इसका उपयोग यह सुनिश्चित करने के लिए किया जाता है कि उत्पन्न परिणामों की यादृच्छिकता पर उनका प्रभाव हो। एल्गोरिथम के इस घटक के बिना, प्रत्येक दांव के परिणाम पर केवल सर्वर सीड का ही पूर्ण प्रभाव होगा।',
    clientSeed2: 'सभी खिलाड़ी यादृच्छिक आगामी परिणामों की एक नई श्रृंखला बनाने के लिए अपने क्लाइंट सीड को नियमित रूप से संपादित और परिवर्तित करने के लिए स्वतंत्र हैं। यह सुनिश्चित करता है कि खिलाड़ी का परिणाम निर्माण पर पूर्ण नियंत्रण हो, ठीक वैसे ही जैसे किसी भौतिक कैसीनो में डेक को काटना।',
    clientSeed3: 'पंजीकरण के दौरान, आपके ब्राउज़र द्वारा आपके लिए एक क्लाइंट सीड बनाया जाता है, ताकि यह सुनिश्चित हो सके कि साइट के साथ आपका प्रारंभिक अनुभव निर्बाध रहे। हालाँकि यह यादृच्छिक रूप से उत्पन्न क्लाइंट सीड उपयुक्त माना जाता है, हम दृढ़ता से अनुशंसा करते हैं कि आप अपना स्वयं का चुनें, ताकि आपका प्रभाव यादृच्छिकता में शामिल हो।',
    clientSeed4: 'आप इसे निष्पक्षता मॉडल के माध्यम से कर सकते हैं।',
    nonce: 'नॉन्स',
    nonce1: 'नॉन्स बस एक संख्या है जो हर नए दांव के साथ बढ़ती है। SHA256 क्रिप्टोग्राफ़िक फ़ंक्शन की प्रकृति के कारण, यह हर बार एक नया परिणाम उत्पन्न करता है, बिना कोई नया क्लाइंट सीड और सर्वर सीड उत्पन्न किए।',
    nonce2: 'नॉन्स का कार्यान्वयन यह सुनिश्चित करता है कि हम आपके क्लाइंट सीड और सर्वर सीड युग्म के प्रति प्रतिबद्ध रहें, जबकि प्रत्येक दांव के लिए नए परिणाम उत्पन्न करते रहें।',
    cursor: 'कर्सर (वृद्धिशील संख्या)',
    cursor1: 'हम एक गेम परिणाम उत्पन्न करने के लिए 4 बाइट्स डेटा का उपयोग करते हैं, और क्योंकि SHA256 32 बाइट्स तक सीमित है, इसलिए हम कर्सर के इस कार्यान्वयन का उपयोग अपने प्रमाणित निष्पक्ष एल्गोरिथम को संशोधित किए बिना अधिक गेम इवेंट बनाने की क्षमता प्रदान करने के लिए करते हैं।',
    cursor2: 'कर्सर केवल तभी दोहराया जाता है जब खेले जा रहे गेम में 8 से अधिक संभावित परिणामों की आवश्यकता होती है। उदाहरण के लिए: जब हमें ब्लैकजैक के खेल में 8 से अधिक कार्डों का उपयोग करने की आवश्यकता होती है।',
    cursor3: 'कर्सर 0 से शुरू होता है और HMAC_SHA256 फ़ंक्शन द्वारा हर बार 32 बाइट्स लौटाए जाने पर 1 से बढ़ जाता है। अगर हमें गेम इवेंट के लिए 8 से ज़्यादा रैंडम नंबर जनरेट करने की ज़रूरत नहीं है, तो कर्सर नहीं बढ़ता क्योंकि कोई अतिरिक्त संभावित गेम परिणाम जनरेट करने की ज़रूरत नहीं है।',
    moreThanOne: '1 से ज़्यादा वृद्धिशील संख्याओं वाले खेल:',
    plinko: 'प्लिं Plinko (संभावित 16 निर्णयों को कवर करने के लिए प्रति खेल 2 वृद्धियाँ)',
    defaultZeroTitle: '1 से ज़्यादा वृद्धिशील संख्याओं वाले खेल (डिफ़ॉल्ट मान 0 के रूप में दर्शाया गया):',
    dice: 'पासा',
    limbo: 'लिम्बो',
  },
  'in-ID': {
    title: 'Pembangkitan Angka Acak',
    desc1: 'Untuk setiap taruhan yang dapat diverifikasi, seed klien, seed server, nonce, dan kursor digunakan sebagai parameter input untuk fungsi pembangkitan angka acak. Fungsi ini menggunakan fungsi hash kriptografi HMAC_SHA256 untuk menghasilkan byte yang kemudian digunakan sebagai dasar bagaimana kami menghasilkan hasil acak yang terbukti adil di platform kami.',
    serverSeed: 'Seed Server',
    serverSeed1: 'Seed server dihasilkan oleh sistem kami sebagai string heksadesimal 64 karakter acak. Anda kemudian akan diberikan hash terenkripsi dari seed server yang dihasilkan sebelum Anda memasang taruhan apa pun. Alasan kami menyediakan seed server dalam bentuk terenkripsi adalah untuk memastikan bahwa seed server yang tidak di-hash tidak dapat diubah oleh operator kasino, dan pemain tidak dapat menghitung hasilnya sebelumnya.',
    serverSeed2: 'Untuk menampilkan server seed dari versi hash-nya, seed tersebut harus diputar oleh pemain, yang memicu penggantiannya dengan seed yang baru dihasilkan.',
    serverSeed3: 'Dari titik ini, Anda dapat memverifikasi bahwa server seed yang di-hash cocok dengan server seed yang tidak di-hash. Proses ini dapat diverifikasi melalui fungsi server seed yang tidak di-hash yang terdapat pada menu di atas.',
    clientSeed: 'Client Seed',
    clientSeed1: 'Client seed adalah milik pemain dan digunakan untuk memastikan mereka memiliki pengaruh terhadap keacakan hasil yang dihasilkan. Tanpa komponen algoritma ini, server seed sendiri akan memiliki pengaruh penuh atas hasil setiap taruhan.',
    clientSeed2: 'Semua pemain bebas mengedit dan mengubah client seed mereka secara berkala untuk membuat rangkaian baru hasil acak yang akan datang. Hal ini memastikan pemain memiliki kendali penuh atas hasil yang dihasilkan, mirip dengan memotong kartu di kasino konvensional.',
    clientSeed3: 'Saat pendaftaran, client seed akan dibuat untuk Anda oleh peramban Anda, untuk memastikan pengalaman awal Anda dengan situs ini tidak terganggu. Meskipun client seed yang dihasilkan secara acak ini dianggap sesuai, kami sangat menyarankan Anda memilih milik Anda sendiri, sehingga pengaruh Anda juga diperhitungkan dalam keacakan tersebut.',
    clientSeed4: 'Anda dapat melakukan ini melalui modal fairness.',
    nonce: 'Nonce',
    nonce1: 'Nonce hanyalah angka yang bertambah setiap kali taruhan baru dibuat. Karena sifat fungsi kriptografi SHA256, ini menghasilkan hasil yang benar-benar baru setiap kali, tanpa harus menghasilkan seed klien dan seed server baru.',
    nonce2: 'Implementasi nonce memastikan kami tetap berkomitmen pada pasangan seed klien dan seed server Anda, sekaligus menghasilkan hasil baru untuk setiap taruhan yang dipasang.',
    cursor: 'Kursor (Angka Inkremental)',
    cursor1: 'Kami menggunakan 4 byte data untuk menghasilkan satu hasil permainan, dan karena SHA256 dibatasi hingga 32 byte, kami menggunakan implementasi kursor ini agar kami dapat membuat lebih banyak kejadian permainan tanpa harus memodifikasi algoritma kami yang terbukti adil.',
    cursor2: 'Kursor hanya diulang ketika permainan yang dimainkan membutuhkan lebih dari 8 kemungkinan hasil (32 byte / 4 byte). Misalnya: ketika kami perlu menggunakan lebih dari 8 kartu dalam permainan blackjack.',
    cursor3: 'Kursor dimulai dari 0 dan bertambah 1 setiap kali 32 byte dikembalikan oleh fungsi HMAC_SHA256. Jika kita tidak memerlukan lebih dari 8 angka acak untuk dibangkitkan untuk kejadian permainan, maka kursor tidak akan bertambah karena tidak perlu membangkitkan kemungkinan hasil permainan tambahan.',
    moreThanOne: 'Permainan dengan Lebih dari 1 Angka Inkremental:',
    plinko: 'Plinko (2 kenaikan per permainan untuk mencakup kemungkinan 16 keputusan)',
    defaultZeroTitle: 'Permainan dengan Lebih dari 1 Angka Inkremental (Direpresentasikan sebagai Nilai Default 0):',
    dice: 'Dadu',
    limbo: 'Limbo',
  },
  'pt-BR': {
    title: 'Geração de Números Aleatórios',
    desc1: 'Para cada aposta verificável, uma semente do cliente, uma semente do servidor, um nonce e um cursor são usados como parâmetros de entrada para a função de geração de números aleatórios. Esta função utiliza a função hash criptográfica HMAC_SHA256 para gerar bytes que são então usados como base para a forma como geramos resultados aleatórios comprovadamente justos em nossa plataforma.',
    serverSeed: 'Semente do servidor',
    serverSeed1: 'A semente do servidor é gerada pelo nosso sistema como uma sequência hexadecimal aleatória de 64 caracteres. Em seguida, você recebe um hash criptografado dessa semente do servidor gerada antes de fazer qualquer aposta. O motivo de fornecermos a semente do servidor em sua forma criptografada é garantir que a semente não criptografada não possa ser alterada pelo operador do cassino e que o jogador não possa calcular os resultados antecipadamente.',
    serverSeed2: 'Para revelar a semente do servidor a partir de sua versão criptografada, a semente deve ser rotacionada pelo jogador, o que aciona sua substituição por uma semente recém-gerada.',
    serverSeed3: 'A partir deste ponto, você poderá verificar se a semente do servidor criptografada corresponde à semente do servidor não criptografada. Esse processo pode ser verificado por meio da função de semente do servidor não criptografada, encontrada no menu acima.',
    clientSeed: 'Semente do cliente',
    clientSeed1: 'A semente do cliente pertence ao jogador e é usada para garantir que ele tenha influência na aleatoriedade dos resultados gerados. Sem esse componente do algoritmo, a semente do servidor sozinha teria controle total sobre o resultado de cada aposta.',
    clientSeed2: 'Todos os jogadores têm a liberdade de editar e alterar regularmente a semente do seu cliente para criar uma nova cadeia de resultados aleatórios futuros. Isso garante que o jogador tenha controle absoluto sobre a geração do resultado, semelhante a cortar o baralho em um cassino físico.',
    clientSeed3: 'Durante o cadastro, seu navegador cria um código de cliente para você, garantindo que sua experiência inicial no site ocorra sem interrupções. Embora esse código de cliente gerado aleatoriamente seja considerado adequado, recomendamos que você escolha o seu próprio, para que sua influência seja incluída na aleatoriedade.',
    clientSeed4: 'Você pode fazer isso através da janela modal de equidade.',
    nonce: 'Nonce',
    nonce1: 'O nonce é simplesmente um número que incrementa a cada nova aposta realizada. Devido à natureza da função criptográfica SHA256, isso cria um resultado completamente novo a cada vez, sem a necessidade de gerar uma nova semente de cliente e uma nova semente de servidor.',
    nonce2: 'A implementação do nonce garante que permaneçamos fiéis ao seu par de seed do cliente e seed do servidor, enquanto geramos novos resultados para cada aposta realizada.',
    cursor: 'Cursor (Número Incremental)',
    cursor1: 'Usamos 4 bytes de dados para gerar um único resultado de jogo e, como o SHA256 é limitado a 32 bytes, utilizamos essa implementação de um cursor para nos dar a capacidade de criar mais eventos de jogo sem precisar modificar nosso algoritmo comprovadamente justo.',
    cursor2: 'O cursor só é iterado quando o jogo em questão exige a geração de mais de 8 resultados possíveis. Por exemplo: quando precisamos usar mais de 8 cartas em um jogo de blackjack.',
    cursor3: 'O cursor começa em 0 e é incrementado em 1 a cada vez que os 32 bytes são retornados pela função HMAC_SHA256. Se não precisarmos gerar mais de 8 números aleatórios para os eventos do jogo, o cursor não é incrementado, pois não há necessidade de gerar resultados adicionais possíveis para o jogo.',
    moreThanOne: 'Jogos com mais de um número incremental:',
    plinko: 'Plinko (2 incrementos por jogo para cobrir 16 decisões possíveis)',
    defaultZeroTitle: 'Jogos com mais de um número incremental (representado pelo valor padrão 0):',
    dice: 'Dados',
    limbo: 'Limbo',
  },
  'tl-PH': {
    title: 'Random na Pagbuo ng Numero',
    desc1: 'Para sa bawat nabe-verify na taya, isang client seed, isang server seed, isang nonce at isang cursor ang ginagamit bilang input parameters para sa random na pagbuo ng numero function. Ginagamit ng function na ito ang cryptographic hash function HMAC_SHA256 upang makabuo ng mga byte na kung saan ay gagamitin bilang pundasyon para sa kung paano kami nakakabuo ng patas na random na resulta sa aming platform.',
    serverSeed: 'Binhi ng Server',
    serverSeed1: 'Ang binhi ng server ay nabuo ng aming system bilang isang random na 64-character na hex string. Pagkatapos ay bibigyan ka ng naka-encrypt na hash ng nabuong binhi ng server bago ka maglagay ng anumang taya. Ang dahilan kung bakit binibigyan ka namin ng naka-encrypt na anyo ng binhi ng server ay upang matiyak na ang hindi na-hash na binhi ng server ay hindi mababago ng operator ng casino, at na hindi makalkula ng manlalaro ang mga resulta nang maaga.',
    serverSeed2: 'Upang ipakita ang binhi ng server mula sa na-hash na bersyon nito, ang binhi ay dapat na paikutin ng player, na nag-trigger sa pagpapalit nito ng isang bagong nabuong binhi.',
    serverSeed3: 'Mula sa puntong ito, mabe-verify mo na ang hashed server seed ay tumutugma sa un-hashed server seed. Maaaring ma-verify ang prosesong ito sa pamamagitan ng un-hashed server seed function na makikita sa menu sa itaas.',
    clientSeed: 'Binhi ng Kliyente',
    clientSeed1: 'Ang binhi ng kliyente ay pag-aari ng manlalaro at ginagamit upang matiyak na mayroon silang impluwensya sa randomness ng mga resultang nabuo. Kung wala ang bahaging ito ng algorithm, ang server seed lang ang magkakaroon ng kumpletong leverage sa kinalabasan ng bawat taya.',
    clientSeed2: 'Ang lahat ng mga manlalaro ay malayang mag-edit at magpalit ng kanilang binhi ng kliyente nang regular upang lumikha ng isang bagong hanay ng mga random na paparating na resulta. Tinitiyak nito na ang manlalaro ay may ganap na kontrol sa pagbuo ng resulta, katulad ng pagputol ng deck sa isang brick and mortar casino.',
    clientSeed3: 'Sa panahon ng pagpaparehistro, ang isang client seed ay ginawa para sa iyo ng iyong browser, upang matiyak na ang iyong unang karanasan sa site ay hindi mapuputol. Habang ang random na nabuong binhi ng kliyente ay itinuturing na angkop, lubos naming inirerekomenda na piliin mo ang iyong sarili, upang ang iyong impluwensya ay maisama sa randomness.',
    clientSeed4: 'Magagawa mo ito sa pamamagitan ng fairness modal.',
    nonce: 'Nonce',
    nonce1: 'Ang nonce ay isang numero lamang na tumataas habang ginagawa ang bawat bagong taya. Dahil sa likas na katangian ng SHA256 cryptographic function, lumilikha ito ng ganap na bagong resulta sa bawat pagkakataon, nang hindi kinakailangang bumuo ng bagong client seed at server seed.',
    nonce2: 'Ang pagpapatupad ng nonce, ay nagsisiguro na mananatili kaming nakatuon sa iyong client seed at server seed pair, habang bumubuo ng mga bagong resulta para sa bawat taya na inilagay.',
    cursor: 'Cursor (Incremental Number)',
    cursor1: 'Gumagamit kami ng 4 na byte ng data upang makabuo ng isang resulta ng laro, at dahil ang SHA256 ay limitado sa 32 byte, ginagamit namin ang pagpapatupad na ito ng isang cursor upang bigyan kami ng kakayahang lumikha ng higit pang mga kaganapan sa laro nang hindi kinakailangang baguhin ang aming pinatunayang patas na algorithm.',
    cursor2: 'Ang cursor ay inuulit lamang kapag ang larong nilalaro ay nangangailangan ng pagbuo ng higit sa 8 na posibleng mga resulta. Halimbawa: kapag kailangan nating gumamit ng higit sa 8 card sa isang laro ng blackjack.',
    cursor3: 'Magsisimula ang cursor bilang 0 at tataas ng 1 sa tuwing ibabalik ng HMAC_SHA256 function ang 32 bytes. Kung hindi namin hinihiling na mabuo ang higit sa 8 random na numero para sa mga event ng laro, hindi tataas ang cursor dahil hindi na kailangang bumuo ng anumang karagdagang posibleng resulta ng laro.',
    moreThanOne: 'Mga Larong may Higit sa 1 Incremental Number:',
    plinko: 'Plinko (2 increments bawat laro para masakop ang posibleng 16 na desisyon)',
    defaultZeroTitle: 'Mga Larong may Higit sa 1 Incremental Number (Kinatawan bilang Default na Halaga 0):',
    dice: 'Dice',
    limbo: 'Limbo',
  },
  'es-ES': {
    title: 'Generación de números aleatorios',
    desc1: 'Para cada apuesta verificable, se utilizan como parámetros de entrada para la función de generación de números aleatorios: una semilla del cliente, una semilla del servidor, un nonce y un cursor. Esta función utiliza la función hash criptográfica HMAC_SHA256 para generar bytes que luego se utilizan como base para generar resultados aleatorios demostrablemente justos en nuestra plataforma.',
    serverSeed: 'Semilla del servidor',
    serverSeed1: 'Nuestro sistema genera la semilla del servidor como una cadena hexadecimal aleatoria de 64 caracteres. Antes de realizar cualquier apuesta, se le proporciona un hash cifrado de dicha semilla. Le proporcionamos la semilla del servidor cifrada para garantizar que el operador del casino no pueda modificarla y que el jugador no pueda calcular los resultados de antemano.',
    serverSeed2: 'Para revelar la semilla del servidor a partir de su versión cifrada, el jugador debe rotar la semilla, lo que provoca su reemplazo por una semilla recién generada.',
    serverSeed3: 'Desde este punto, puede verificar que la semilla del servidor cifrada coincide con la semilla del servidor sin cifrar. Este proceso se puede verificar mediante la función de semilla del servidor sin cifrar que se encuentra en el menú superior.',
    clientSeed: 'Semilla del cliente',
    clientSeed1: 'La semilla del cliente pertenece al jugador y se utiliza para garantizar que este influya en la aleatoriedad de los resultados generados. Sin este componente del algoritmo, la semilla del servidor por sí sola tendría control absoluto sobre el resultado de cada apuesta.',
    clientSeed2: 'Todos los jugadores pueden editar y cambiar su semilla de cliente periódicamente para crear una nueva cadena de resultados aleatorios. Esto garantiza que el jugador tenga un control absoluto sobre la generación del resultado, similar a cuando se corta la baraja en un casino físico.',
    clientSeed3: 'Durante el registro, tu navegador genera automáticamente una clave de cliente para garantizar una experiencia inicial sin interrupciones en el sitio. Si bien esta clave generada aleatoriamente se considera adecuada, te recomendamos encarecidamente que elijas la tuya propia para que tu opinión influya en la aleatoriedad.',
    clientSeed4: 'Puedes hacerlo a través del modal de equidad.',
    nonce: 'Nonce',
    nonce1: 'El nonce es simplemente un número que se incrementa con cada nueva apuesta. Gracias a la naturaleza de la función criptográfica SHA256, esto genera un resultado completamente nuevo cada vez, sin necesidad de generar una nueva semilla de cliente ni de servidor.',
    nonce2: 'La implementación del nonce garantiza que mantengamos nuestro compromiso con el par de semillas de cliente y servidor, al tiempo que generamos nuevos resultados para cada apuesta realizada.',
    cursor: 'Cursor (Número incremental)',
    cursor1: 'Utilizamos 4 bytes de datos para generar un único resultado de juego, y dado que SHA256 está limitado a 32 bytes, utilizamos esta implementación de un cursor para poder crear más eventos de juego sin tener que modificar nuestro algoritmo demostrablemente justo.',
    cursor2: 'El cursor solo se itera cuando el juego requiere generar más de 8 (32 bytes / 4 bytes) resultados posibles. Por ejemplo: cuando se necesitan más de 8 cartas en una partida de blackjack.',
    cursor3: 'El cursor comienza en 0 y se incrementa en 1 cada vez que la función HMAC_SHA256 devuelve los 32 bytes. Si no se requieren más de 8 números aleatorios para generar los eventos del juego, el cursor no se incrementa, ya que no es necesario generar resultados adicionales.',
    moreThanOne: 'Juegos con más de un número incremental:',
    plinko: 'Plinko (2 incrementos por partida para cubrir las 16 decisiones posibles)',
    defaultZeroTitle: 'Juegos con más de un número incremental (representado como valor predeterminado 0):',
    dice: 'Dados',
    limbo: 'Limbo',
  },
}

const code = `// Random number generation based on following inputs: serverSeed, clientSeed, nonce and cursor
function byteGenerator({ serverSeed, clientSeed, nonce, cursor }) {
  let currentRound = Math.floor(cursor / 32);
  let currentRoundCursor = cursor % 32;

  while (true) {
    const hmac = createHmac('sha256', serverSeed);
    hmac.update(\`\${clientSeed}:\${nonce}:\${currentRound}\`);
    const buffer = hmac.digest();

    while (currentRoundCursor < 32) {
      yield Number(buffer[currentRoundCursor]);
      currentRoundCursor += 1;
    }
    currentRoundCursor = 0;
    currentRound += 1;
  }
}`
</script>

<template>
  <div>
    <div class="text-[#fff] text-[16px] font-semibold leading-[1.32] @md:text-[28px]">
      {{ t[lang].title }}
    </div>

    <div class="text-[#b1bad3] mt-[14px] text-[14px] leading-[1.5]" v-html="t[lang].desc1.replace('random number generation', `<a class='text-[#fff]' href='https://en.wikipedia.org/wiki/Random_number_generation' target='_blank'>random number generation <BaseIcon class='text-[12px]' name='uni-jump-page' /></a>`).replace('HMAC_SHA256', `<a class='text-[#fff]' href='https://en.wikipedia.org/wiki/HMAC' target='_blank'>HMAC_SHA256 <BaseIcon class='text-[12px]' name='uni-jump-page' /></a>`)" />

    <div class="text-[#fff] scroll-x bg-[#213743] mt-[14px] rounded-[4px] p-[14px] text-[14px] leading-[1.5]">
      <pre><code>{{ code }}</code></pre>
    </div>

    <!-- Server Seed -->
    <div class="text-[#fff] mt-[14px] text-[16px] font-semibold leading-[1.32] @md:text-[28px]">
      {{ t[lang].serverSeed }}
    </div>
    <div class="text-[#b1bad3] mt-[14px] text-[14px] leading-[1.5]" v-text="t[lang].serverSeed1" />
    <div class="text-[#b1bad3] mt-[14px] text-[14px] leading-[1.5]" v-text="t[lang].serverSeed2" />
    <div class="text-[#b1bad3] mt-[14px] text-[14px] leading-[1.5]" v-text="t[lang].serverSeed3" />

    <!-- Client Seed -->
    <div class="text-[#fff] mt-[14px] text-[16px] font-semibold leading-[1.32] @md:text-[28px]">
      {{ t[lang].clientSeed }}
    </div>
    <div class="text-[#b1bad3] mt-[14px] text-[14px] leading-[1.5]" v-text="t[lang].clientSeed1" />
    <div class="text-[#b1bad3] mt-[14px] text-[14px] leading-[1.5]" v-text="t[lang].clientSeed2" />
    <div class="text-[#b1bad3] mt-[14px] text-[14px] leading-[1.5]" v-text="t[lang].clientSeed3" />
    <div class="text-[#b1bad3] mt-[14px] text-[14px] leading-[1.5]" v-text="t[lang].clientSeed4" />

    <!-- Nonce -->
    <div class="text-[#fff] mt-[14px] text-[16px] font-semibold leading-[1.32] @md:text-[28px]">
      {{ t[lang].nonce }}
    </div>
    <div class="text-[#b1bad3] mt-[14px] text-[14px] leading-[1.5]" v-text="t[lang].nonce1" />
    <div class="text-[#b1bad3] mt-[14px] text-[14px] leading-[1.5]" v-text="t[lang].nonce2" />

    <!-- Cursor -->
    <div class="text-[#fff] mt-[14px] text-[16px] font-semibold leading-[1.32] @md:text-[28px]">
      {{ t[lang].cursor }}
    </div>
    <div class="text-[#b1bad3] mt-[14px] text-[14px] leading-[1.5]" v-text="t[lang].cursor1" />
    <div class="text-[#b1bad3] mt-[14px] text-[14px] leading-[1.5]" v-text="t[lang].cursor2" />
    <div class="text-[#b1bad3] mt-[14px] text-[14px] leading-[1.5]" v-text="t[lang].cursor3" />

    <!-- Games list -->
    <div class="text-[#fff] mt-[14px] text-[16px] font-semibold leading-[1.32]">
      {{ t[lang].moreThanOne }}
    </div>
    <ul class="ml-[32px] mt-[14px] list-disc text-[14px] leading-[1.32]">
      <li class="mb-[8px]" v-text="t[lang].plinko" />
    </ul>

    <div class="text-[#fff] mt-[14px] text-[16px] font-semibold leading-[1.32]">
      {{ t[lang].defaultZeroTitle }}
    </div>
    <ul class="ml-[32px] mt-[14px] list-disc text-[14px]">
      <li class="mb-[8px] leading-[1.32]" v-text="t[lang].dice" />
      <li class="mb-[8px] leading-[1.32]" v-text="t[lang].limbo" />
    </ul>
  </div>
</template>

<style lang="scss" scoped>
.scroll-x {
  overflow-x: auto;
}
pre code {
  white-space: pre;
}
</style>
